### ISSUE TITLE
Avo is not loading (license validation is failing)

### ISSUE THREAD

**Issue by mid** [avo-hq/avo#1025]
### Describe the bug

Getting the following exception:
```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=52.0.219.18:443 state=error: certificate verify failed (certificate has expired)
  from net-protocol (0.1.3) lib/net/protocol.rb:46:in `connect_nonblock'
  from net-protocol (0.1.3) lib/net/protocol.rb:46:in `ssl_socket_connect'
  from net/http.rb:1048:in `connect'
  from net/http.rb:976:in `do_start'
  from net/http.rb:965:in `start'
  from net/http.rb:1530:in `request'
  from sentry-ruby-core (5.3.1) lib/sentry/net/http.rb:29:in `request'
  from httparty (0.20.0) lib/httparty/request.rb:152:in `perform'
  from httparty (0.20.0) lib/httparty.rb:613:in `perform_request'
  from httparty (0.20.0) lib/httparty.rb:543:in `post'
  from httparty (0.20.0) lib/httparty.rb:650:in `post'
  from avo (2.9.0) lib/avo/licensing/h_q.rb:159:in `perform_request'
  from avo (2.9.0) lib/avo/licensing/h_q.rb:135:in `perform_and_cache_request'
  from avo (2.9.0) lib/avo/licensing/h_q.rb:116:in `make_request'
  from avo (2.9.0) lib/avo/licensing/h_q.rb:25:in `response'
  from avo (2.9.0) lib/avo/app.rb:41:in `init'
  from avo (2.9.0) app/controllers/avo/application_controller.rb:30:in `init_app'
  from activesupport (7.0.3) lib/active_support/callbacks.rb:400:in `block in make_lambda'
  from activesupport (7.0.3) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
  from actionpack (7.0.3) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
  from activesupport (7.0.3) lib/active_support/callbacks.rb:200:in `block in halting'
  from activesupport (7.0.3) lib/active_support/callbacks.rb:595:in `block in invoke_before'
  from activesupport (7.0.3) lib/active_support/callbacks.rb:595:in `each'
  from activesupport (7.0.3) lib/active_support/callbacks.rb:595:in `invoke_before'
  from activesupport (7.0.3) lib/active_support/callbacks.rb:106:in `run_callbacks'
  from actionpack (7.0.3) lib/abstract_controller/callbacks.rb:233:in `process_action'
  from actionpack (7.0.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
  from actionpack (7.0.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
  from activesupport (7.0.3) lib/active_support/notifications.rb:206:in `block in instrument'
  from activesupport (7.0.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  from sentry-rails (5.3.1) lib/sentry/rails/tracing.rb:54:in `instrument'
  from activesupport (7.0.3) lib/active_support/notifications.rb:206:in `instrument'
  from actionpack (7.0.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
  from actionpack (7.0.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
  from activerecord (7.0.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  from actionpack (7.0.3) lib/abstract_controller/base.rb:151:in `process'
  from actionview (7.0.3) lib/action_view/rendering.rb:39:in `process'
  from actionpack (7.0.3) lib/action_controller/metal.rb:188:in `dispatch'
  from actionpack (7.0.3) lib/action_controller/metal.rb:251:in `dispatch'
  from actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
  from actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
  from actionpack (7.0.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
  from actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
  from railties (7.0.3) lib/rails/engine.rb:530:in `call'
  from railties (7.0.3) lib/rails/railtie.rb:226:in `public_send'
  from railties (7.0.3) lib/rails/railtie.rb:226:in `method_missing'
  from actionpack (7.0.3) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
  from actionpack (7.0.3) lib/action_dispatch/routing/mapper.rb:48:in `serve'
  from actionpack (7.0.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
  from actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `each'
  from actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `serve'
  from actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
  from omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
  from omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
  from warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
  from warden (1.2.9) lib/warden/manager.rb:34:in `catch'
  from warden (1.2.9) lib/warden/manager.rb:34:in `call'
  from rack (2.2.3.1) lib/rack/static.rb:161:in `call'
  from rack (2.2.3.1) lib/rack/tempfile_reaper.rb:15:in `call'
  from rack (2.2.3.1) lib/rack/etag.rb:27:in `call'
  from rack (2.2.3.1) lib/rack/conditional_get.rb:27:in `call'
  from rack (2.2.3.1) lib/rack/head.rb:12:in `call'
  from actionpack (7.0.3) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
  from actionpack (7.0.3) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
  from rack (2.2.3.1) lib/rack/session/abstract/id.rb:266:in `context'
  from rack (2.2.3.1) lib/rack/session/abstract/id.rb:260:in `call'
  from actionpack (7.0.3) lib/action_dispatch/middleware/cookies.rb:697:in `call'
  from actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
  from activesupport (7.0.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
  from actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  from sentry-rails (5.3.1) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
  from actionpack (7.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
  from sentry-ruby-core (5.3.1) lib/sentry/rack/capture_exceptions.rb:26:in `block (2 levels) in call'
  from sentry-ruby-core (5.3.1) lib/sentry/hub.rb:199:in `with_session_tracking'
  from sentry-ruby-core (5.3.1) lib/sentry-ruby.rb:351:in `with_session_tracking'
  from sentry-ruby-core (5.3.1) lib/sentry/rack/capture_exceptions.rb:17:in `block in call'
  from sentry-ruby-core (5.3.1) lib/sentry/hub.rb:59:in `with_scope'
  from sentry-ruby-core (5.3.1) lib/sentry-ruby.rb:331:in `with_scope'
  from sentry-ruby-core (5.3.1) lib/sentry/rack/capture_exceptions.rb:16:in `call'
  from actionpack (7.0.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
  from railties (7.0.3) lib/rails/rack/logger.rb:40:in `call_app'
  from railties (7.0.3) lib/rails/rack/logger.rb:25:in `block in call'
  from activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `block in tagged'
  from activesupport (7.0.3) lib/active_support/tagged_logging.rb:38:in `tagged'
  from activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `tagged'
  from railties (7.0.3) lib/rails/rack/logger.rb:25:in `call'
  from actionpack (7.0.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
  from request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
  from actionpack (7.0.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
  from rack (2.2.3.1) lib/rack/method_override.rb:24:in `call'
  from rack (2.2.3.1) lib/rack/runtime.rb:22:in `call'
  from actionpack (7.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
  from actionpack (7.0.3) lib/action_dispatch/middleware/static.rb:23:in `call'
  from rack (2.2.3.1) lib/rack/sendfile.rb:110:in `call'
  from actionpack (7.0.3) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
  from railties (7.0.3) lib/rails/engine.rb:530:in `call'
  from puma (5.6.4) lib/puma/configuration.rb:252:in `call'
  from puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
  from puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
  from puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
  from puma (5.6.4) lib/puma/server.rb:441:in `process_client'
  from puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

It seems that the licensing server is down.

**Comment by adrianthedev** [comment]
I'm on it. Fixing it in 10 minutes. Apologies for the downtime.
