### ISSUE TITLE
Tool generator results in root_path error 

### ISSUE THREAD

**Issue by coffenbacher** [avo-hq/avo#1051]
I'm getting an error when I run:

`bin/rails generate avo:tool example`

Not quite sure what to look into from here or what information would be helpful for debugging...

```
Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/avo-2.10.0/lib/avo/app.rb:34:in `root_path': undefined method `avo' for nil:NilClass (NoMethodError)

        Avo::Services::URIService.parse(view_context.avo.root_url.to_s)
                                                    ^^^^
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/avo-2.10.0/lib/avo/configuration.rb:126:in `computed_root_path'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/avo-2.10.0/lib/avo/configuration.rb:112:in `namespace'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/avo-2.10.0/lib/generators/avo/tool_generator.rb:42:in `handle'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `block in invoke_all'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `each'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `map'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `invoke_all'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/group.rb:232:in `dispatch'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/generators.rb:263:in `invoke'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<top (required)>'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/coffenbacher/workspace/torq/torq-api/bin/rails:9:in `<top (required)>'
        from <internal:/Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/coffenbacher/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from -e:1:in `<main>'
```

**Comment by adrianthedev** [comment]
Thanks, @coffenbacher. This should be fixed in https://github.com/avo-hq/avo/pull/1033. Avo gets released every Tuesday.

Until then please do the following to temporarily fix it on your end

- in your app run `bundle open avo`
- navigate to `lib/avo/configuration.rb` line ~ 126 on `def computed_root_path` method
- change `Avo::App.root_path` to `Avo.configuration.root_path`
- close the editor and try the command again
