### ISSUE TITLE
Application with 'card' resource

### ISSUE THREAD

**Issue by angel-checkealos** [avo-hq/avo#1364]
### Describe the bug
In my application I have a model called 'card'. I have found the next issue:
When I create a dashboard and a card for the dasboard everything work fine, but when I try to load the dashboard page in console I get the next.

```
Unpermitted parameters: :turbo_frame, :range, :locale. Context: { controller: Avo::HomeController, action: failed_to_load, request: #<ActionDispatch::Request:0x00007f6cd93e5fd8>, params: {"turbo_frame"=>"admin_dashboard_users_metric", "src"=>"/es/avo/dashboards/admin_dashboard/cards/admin_dashboard.users_metric?index=0", "range"=>"30", "locale"=>"es", "controller"=>"avo/home", "action"=>"failed_to_load"} }
```
On the other hand the console log the next:
```
Card Load (1.8ms)  SELECT `cards`.* FROM `cards` WHERE `cards`.`id` = NULL LIMIT 1
ActiveRecord::RecordNotFound (Couldn't find Card with 'id'=admin_dashboard):

```
Where `admin_dashboard` is the id of my new dashboard

### Steps to Reproduce
1. Create fresh application with AVO gem
2. Create a dashboard and a simple metric card
3. Go to dashboard page and works fine
4. Add card model `rails g model card` and dashboard works fine
5. Add card resource `rails g avo:resource card`
6. Reload the dashboard URL
7. The card is not printed and in the console get:

```
12:21:45 web.1  | Processing by Avo::CardsController#show as */*
12:21:45 web.1  |   Parameters: {"index"=>"0", "turbo_frame"=>"admin_dashboard_users_metric", "locale"=>"en", "dashboard_id"=>"admin_dashboard", "id"=>"admin_dashboard"}
12:21:45 web.1  | Unpermitted parameters: :index, :turbo_frame, :locale, :dashboard_id, :format. Context: { controller: Avo::CardsController, action: show, request: #<ActionDispatch::Request:0x000000010ddf9dd8>, params: {"index"=>"0", "turbo_frame"=>"admin_dashboard_users_metric", "locale"=>"en", "controller"=>"avo/cards", "action"=>"show", "dashboard_id"=>"admin_dashboard", "id"=>"admin_dashboard", "format"=>"users_metric"} }
12:21:45 web.1  | Completed 500 Internal Server Error in 69ms (ActiveRecord: 62.2ms | Allocations: 5720)
````

### System configuration
**Avo version**: 2.18

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**:
 - [ ] Community
 - [X ] Pro

**Are you using Avo monkey patches or overriding views or view components?**
 - [ ] Yes. If so, please post code samples.
 - [X ] No

#### Impact
 - [ ] High impact
 - [X ] Medium impact
 - [ ] Low impact

#### Urgency
 - [ ] High urgency
 - [X ] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment]
can you please post the error thrown here?

`12:21:45 web.1  | Completed 500 Internal Server Error in 69ms (ActiveRecord: 62.2ms | Allocations: 5720)
`

**Comment by angel-checkealos** [comment]
In the fresh application (created without test) the 500 error is:
```

12:21:45 web.1  | ActiveRecord::StatementInvalid (Mysql2::Error: Table 'avo_test_development.cards' doesn't exist):
12:21:45 web.1  |   
12:21:45 web.1  | mysql2 (0.5.4) lib/mysql2/client.rb:148:in `_query'
12:21:45 web.1  | mysql2 (0.5.4) lib/mysql2/client.rb:148:in `block in query'
12:21:45 web.1  | mysql2 (0.5.4) lib/mysql2/client.rb:147:in `handle_interrupt'
12:21:45 web.1  | mysql2 (0.5.4) lib/mysql2/client.rb:147:in `query'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:632:in `block (2 levels) in raw_execute'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:631:in `block in raw_execute'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:630:in `raw_execute'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:207:in `execute_and_free'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:825:in `column_definitions'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/abstract/schema_statements.rb:116:in `columns'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/schema_cache.rb:117:in `block in columns'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/schema_cache.rb:116:in `fetch'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/schema_cache.rb:116:in `columns'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/schema_cache.rb:125:in `block in columns_hash'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/schema_cache.rb:124:in `fetch'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/connection_adapters/schema_cache.rb:124:in `columns_hash'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/model_schema.rb:580:in `load_schema!'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/attributes.rb:264:in `load_schema!'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/encryption/encryptable_record.rb:122:in `load_schema!'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/model_schema.rb:566:in `block in load_schema'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/model_schema.rb:563:in `synchronize'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/model_schema.rb:563:in `load_schema'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/model_schema.rb:429:in `attribute_types'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/model_schema.rb:455:in `type_for_attribute'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/type_caster/map.rb:16:in `type_for_attribute'
12:21:45 web.1  | activerecord (7.0.4) lib/arel/table.rb:107:in `type_for_attribute'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/table_metadata.rb:18:in `type'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/relation/predicate_builder.rb:59:in `build'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/relation/predicate_builder.rb:54:in `[]'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/relation/predicate_builder.rb:126:in `block in expand_from_hash'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/relation/predicate_builder.rb:79:in `each'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/relation/predicate_builder.rb:79:in `flat_map'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/relation/predicate_builder.rb:79:in `expand_from_hash'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/relation/predicate_builder.rb:25:in `build_from_hash'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/relation/query_methods.rb:1313:in `build_where_clause'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/relation/query_methods.rb:756:in `where!'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/relation/query_methods.rb:751:in `where'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/querying.rb:22:in `where'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/core.rb:280:in `block in find'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/statement_cache.rb:133:in `create'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/core.rb:434:in `block in cached_find_by_statement'
12:21:45 web.1  | concurrent-ruby (1.1.10) lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:31:in `compute_if_absent'
12:21:45 web.1  | concurrent-ruby (1.1.10) lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:25:in `block in compute_if_absent'
12:21:45 web.1  | concurrent-ruby (1.1.10) lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:25:in `synchronize'
12:21:45 web.1  | concurrent-ruby (1.1.10) lib/concurrent-ruby/concurrent/collection/map/mri_map_backend.rb:25:in `compute_if_absent'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/core.rb:434:in `cached_find_by_statement'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/core.rb:279:in `find'
12:21:45 web.1  | avo (2.18.0) app/controllers/avo/application_controller.rb:124:in `set_model'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:400:in `block in make_lambda'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:180:in `block (2 levels) in halting_and_conditional'
12:21:45 web.1  | actionpack (7.0.4) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:181:in `block in halting_and_conditional'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `block in invoke_before'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `each'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `invoke_before'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:116:in `block in run_callbacks'
12:21:45 web.1  | i18n (1.12.0) lib/i18n.rb:322:in `with_locale'
12:21:45 web.1  | avo (2.18.0) app/controllers/avo/application_controller.rb:323:in `set_avo_locale'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
12:21:45 web.1  | actiontext (7.0.4) lib/action_text/rendering.rb:20:in `with_renderer'
12:21:45 web.1  | actiontext (7.0.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `instance_exec'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:138:in `run_callbacks'
12:21:45 web.1  | actionpack (7.0.4) lib/abstract_controller/callbacks.rb:233:in `process_action'
12:21:45 web.1  | actionpack (7.0.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
12:21:45 web.1  | actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'
12:21:45 web.1  | actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
12:21:45 web.1  | actionpack (7.0.4) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
12:21:45 web.1  | actionpack (7.0.4) lib/abstract_controller/base.rb:151:in `process'
12:21:45 web.1  | actionview (7.0.4) lib/action_view/rendering.rb:39:in `process'
12:21:45 web.1  | actionpack (7.0.4) lib/action_controller/metal.rb:188:in `dispatch'
12:21:45 web.1  | actionpack (7.0.4) lib/action_controller/metal.rb:251:in `dispatch'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
12:21:45 web.1  | railties (7.0.4) lib/rails/engine.rb:530:in `call'
12:21:45 web.1  | railties (7.0.4) lib/rails/railtie.rb:226:in `public_send'
12:21:45 web.1  | railties (7.0.4) lib/rails/railtie.rb:226:in `method_missing'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
12:21:45 web.1  | rack (2.2.4) lib/rack/static.rb:161:in `call'
12:21:45 web.1  | warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
12:21:45 web.1  | warden (1.2.9) lib/warden/manager.rb:34:in `catch'
12:21:45 web.1  | warden (1.2.9) lib/warden/manager.rb:34:in `call'
12:21:45 web.1  | rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
12:21:45 web.1  | rack (2.2.4) lib/rack/etag.rb:27:in `call'
12:21:45 web.1  | rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'
12:21:45 web.1  | rack (2.2.4) lib/rack/head.rb:12:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
12:21:45 web.1  | rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
12:21:45 web.1  | rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/cookies.rb:696:in `call'
12:21:45 web.1  | activerecord (7.0.4) lib/active_record/migration.rb:603:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/callbacks.rb:99:in `run_callbacks'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
12:21:45 web.1  | web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
12:21:45 web.1  | web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
12:21:45 web.1  | web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
12:21:45 web.1  | web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
12:21:45 web.1  | railties (7.0.4) lib/rails/rack/logger.rb:40:in `call_app'
12:21:45 web.1  | railties (7.0.4) lib/rails/rack/logger.rb:25:in `block in call'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/tagged_logging.rb:37:in `tagged'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `tagged'
12:21:45 web.1  | railties (7.0.4) lib/rails/rack/logger.rb:25:in `call'
12:21:45 web.1  | sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
12:21:45 web.1  | rack (2.2.4) lib/rack/method_override.rb:24:in `call'
12:21:45 web.1  | rack (2.2.4) lib/rack/runtime.rb:22:in `call'
12:21:45 web.1  | activesupport (7.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
12:21:45 web.1  | rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
12:21:45 web.1  | actionpack (7.0.4) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
12:21:45 web.1  | railties (7.0.4) lib/rails/engine.rb:530:in `call'
12:21:45 web.1  | puma (5.6.5) lib/puma/configuration.rb:252:in `call'
12:21:45 web.1  | puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
12:21:45 web.1  | puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
12:21:45 web.1  | puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
12:21:45 web.1  | puma (5.6.5) lib/puma/server.rb:443:in `process_client'
12:21:45 web.1  | puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
12:21:45 web.1  | Started GET "/en/avo/failed_to_load?turbo_frame=admin_dashboard_users_metric&src=/en/avo/dashboards/admin_dashboard/cards/admin_dashboard.users_metric?index=0&turbo_frame=admin_dashboard_users_metric" for ::1 at 2022-10-26 12:21:45 +0200

```
but in my application with test (**NOTE: My appliaction is running on docker**), the error is:
```
app-1      |   Card Load (0.9ms)  SELECT `cards`.* FROM `cards` WHERE `cards`.`id` = NULL LIMIT 1
app-1      | Completed 404 Not Found in 17ms (ActiveRecord: 0.9ms | Allocations: 7115)
app-1      | 
app-1      | 
app-1      |   
app-1      | ActiveRecord::RecordNotFound (Couldn't find Card with 'id'=admin_dashboard):
app-1      |   
app-1      | activerecord (7.0.4) lib/active_record/core.rb:284:in `find'
app-1      | avo (2.18.0) app/controllers/avo/application_controller.rb:124:in `set_model'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:400:in `block in make_lambda'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:180:in `block (2 levels) in halting_and_conditional'
app-1      | actionpack (7.0.4) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:181:in `block in halting_and_conditional'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `block in invoke_before'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `each'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `invoke_before'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:116:in `block in run_callbacks'
app-1      | i18n (1.12.0) lib/i18n.rb:322:in `with_locale'
app-1      | avo (2.18.0) app/controllers/avo/application_controller.rb:323:in `set_avo_locale'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
app-1      | actiontext (7.0.4) lib/action_text/rendering.rb:20:in `with_renderer'
app-1      | actiontext (7.0.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `instance_exec'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:138:in `run_callbacks'
app-1      | actionpack (7.0.4) lib/abstract_controller/callbacks.rb:233:in `process_action'
app-1      | actionpack (7.0.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
app-1      | actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
app-1      | activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'
app-1      | activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
app-1      | activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'
app-1      | actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
app-1      | actionpack (7.0.4) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
app-1      | activerecord (7.0.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
app-1      | actionpack (7.0.4) lib/abstract_controller/base.rb:151:in `process'
app-1      | actionview (7.0.4) lib/action_view/rendering.rb:39:in `process'
app-1      | actionpack (7.0.4) lib/action_controller/metal.rb:188:in `dispatch'
app-1      | actionpack (7.0.4) lib/action_controller/metal.rb:251:in `dispatch'
app-1      | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
app-1      | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
app-1      | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
app-1      | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
app-1      | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
app-1      | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
app-1      | railties (7.0.4) lib/rails/engine.rb:530:in `call'
app-1      | railties (7.0.4) lib/rails/railtie.rb:226:in `public_send'
app-1      | railties (7.0.4) lib/rails/railtie.rb:226:in `method_missing'
app-1      | actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
app-1      | actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
app-1      | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
app-1      | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
app-1      | actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
app-1      | actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
app-1      | rack (2.2.4) lib/rack/static.rb:161:in `call'
app-1      | warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
app-1      | warden (1.2.9) lib/warden/manager.rb:34:in `catch'
app-1      | warden (1.2.9) lib/warden/manager.rb:34:in `call'
app-1      | rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
app-1      | rack (2.2.4) lib/rack/etag.rb:27:in `call'
app-1      | rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'
app-1      | rack (2.2.4) lib/rack/head.rb:12:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
app-1      | rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
app-1      | rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/cookies.rb:696:in `call'
app-1      | activerecord (7.0.4) lib/active_record/migration.rb:603:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
app-1      | activesupport (7.0.4) lib/active_support/callbacks.rb:99:in `run_callbacks'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
app-1      | web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
app-1      | web-console (4.2.0) lib/web_console/middleware.rb:19:in `block in call'
app-1      | web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
app-1      | web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
app-1      | railties (7.0.4) lib/rails/rack/logger.rb:40:in `call_app'
app-1      | railties (7.0.4) lib/rails/rack/logger.rb:25:in `block in call'
app-1      | activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
app-1      | activesupport (7.0.4) lib/active_support/tagged_logging.rb:37:in `tagged'
app-1      | activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `tagged'
app-1      | railties (7.0.4) lib/rails/rack/logger.rb:25:in `call'
app-1      | sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
app-1      | rack (2.2.4) lib/rack/method_override.rb:24:in `call'
app-1      | rack (2.2.4) lib/rack/runtime.rb:22:in `call'
app-1      | activesupport (7.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
app-1      | rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
app-1      | actionpack (7.0.4) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
app-1      | railties (7.0.4) lib/rails/engine.rb:530:in `call'
app-1      | puma (5.6.5) lib/puma/configuration.rb:252:in `call'
app-1      | puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
app-1      | puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
app-1      | puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
app-1      | puma (5.6.5) lib/puma/server.rb:443:in `process_client'
app-1      | puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
app-1      | Started GET "/es/avo/failed_to_load?turbo_frame=admin_dashboard_projects_chart&src=/es/avo/dashboards/admin_dashboard/cards/admin_dashboard.projects_chart?index=1&turbo_frame=admin_dashboard_projects_chart" for 172.20.0.1 at 2022-10-26 09:53:03 +0000
app-1      | Cannot render console from 172.20.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
app-1      | Started GET "/es/avo/dashboards/admin_dashboard/cards/admin_dashboard.users_metric?index=0&range=30&turbo_frame=admin_dashboard_users_metric" for 172.20.0.1 at 2022-10-26 09:53:03 +0000

```

**Comment by adrianthedev** [comment]
Yes, there's a conflict with `CardsController` from the resource and the dashboard.

We'll think about how to fix this in the following days.
