### ISSUE TITLE
Zeitwerk::Error after upgrade to 2.19.0

### ISSUE THREAD

**Issue by koppen** [avo-hq/avo#1425]
### Describe the bug

After upgrading our application from avo 2.18.1 to the recently released 2.19.0, we've started seeing

    Zeitwerk::Error in Avo::HomeController#index
    ~/app/avo/dashboards is not a directory

in all our Avo-resource paths. Reverting to 2.18.1 removes the error.

### Steps to Reproduce

1. Upgrade to 2.19
2. Start the server: `rails server`
3. Go to [/avo](http://127.0.0.1:3000/avo)

Honestly, I am not sure that the above is the smallest possible steps, but that's what I've been able to figure out.

### Expected behavior & Actual behavior

I'd expect the actual HomeController to render the index page.

### System configuration
**Avo version**: 2.19

**Rails version**: 7.0.4

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Full stacktrace

```
Zeitwerk::Error in Avo::HomeController#index
~/app/avo/dashboards is not a directory
Extracted source (around line #37):

    abspath = File.expand_path(path)

    raise Zeitwerk::Error.new("#{abspath} is not a directory") unless dir?(abspath)

    cnames = []

Rails.root: ~

zeitwerk (2.6.6) lib/zeitwerk/loader/eager_load.rb:37:in `eager_load_dir'
avo (2.19.0) lib/avo/app.rb:25:in `eager_load'
avo (2.19.0) lib/avo/app.rb:130:in `init_dashboards'
avo (2.19.0) lib/avo/app.rb:70:in `init'
avo (2.19.0) app/controllers/avo/application_controller.rb:34:in `init_app'
activesupport (7.0.4) lib/active_support/callbacks.rb:400:in `block in make_lambda'
activesupport (7.0.4) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
actionpack (7.0.4) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (7.0.4) lib/active_support/callbacks.rb:200:in `block in halting'
activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `block in invoke_before'
activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `each'
activesupport (7.0.4) lib/active_support/callbacks.rb:595:in `invoke_before'
activesupport (7.0.4) lib/active_support/callbacks.rb:116:in `block in run_callbacks'
i18n (1.12.0) lib/i18n.rb:322:in `with_locale'
avo (2.19.0) app/controllers/avo/application_controller.rb:329:in `set_avo_locale'
activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
actiontext (7.0.4) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (7.0.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `instance_exec'
activesupport (7.0.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
activesupport (7.0.4) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.4) lib/abstract_controller/callbacks.rb:233:in `process_action'
actionpack (7.0.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.0.4) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
actionpack (7.0.4) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
activerecord (7.0.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (7.0.4) lib/abstract_controller/base.rb:151:in `process'
actionview (7.0.4) lib/action_view/rendering.rb:39:in `process'
actionpack (7.0.4) lib/action_controller/metal.rb:188:in `dispatch'
actionpack (7.0.4) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
railties (7.0.4) lib/rails/engine.rb:530:in `call'
railties (7.0.4) lib/rails/railtie.rb:226:in `public_send'
railties (7.0.4) lib/rails/railtie.rb:226:in `method_missing'
actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (7.0.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.0) lib/omniauth/builder.rb:44:in `call'
rack (2.2.4) lib/rack/static.rb:161:in `call'
rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.4) lib/rack/etag.rb:27:in `call'
rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.4) lib/rack/head.rb:12:in `call'
actionpack (7.0.4) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/cookies.rb:696:in `call'
activerecord (7.0.4) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.4) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.4) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.4) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.4) lib/rails/rack/logger.rb:25:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.4) lib/rack/method_override.rb:24:in `call'
rack (2.2.4) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
actionpack (7.0.4) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.4) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
honeybadger (5.0.2) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (5.0.2) lib/honeybadger/agent.rb:433:in `with_rack_env'
honeybadger (5.0.2) lib/honeybadger/rack/error_notifier.rb:30:in `call'
honeybadger (5.0.2) lib/honeybadger/rack/user_feedback.rb:31:in `call'
honeybadger (5.0.2) lib/honeybadger/rack/user_informer.rb:21:in `call'
rack-mini-profiler (3.0.0) lib/mini_profiler/profiler.rb:393:in `call'
railties (7.0.4) lib/rails/engine.rb:530:in `call'
puma (6.0.0) lib/puma/configuration.rb:268:in `call'
puma (6.0.0) lib/puma/request.rb:89:in `block in handle_request'
puma (6.0.0) lib/puma/thread_pool.rb:343:in `with_force_shutdown'
puma (6.0.0) lib/puma/request.rb:88:in `handle_request'
puma (6.0.0) lib/puma/server.rb:430:in `process_client'
puma (6.0.0) lib/puma/server.rb:233:in `block in run'
puma (6.0.0) lib/puma/thread_pool.rb:150:in `block in spawn_thread' 
```

Zeitwerk doesn't directly complain:

```
$ rails zeitwerk:check
Hold on, I am eager loading the application.
All is good!
```

The error message is correct in that `app/avo/dashboards` is not a directory:

```
$ ls -l app/avo/dashboards
ls: app/avo/dashboards: No such file or directory
```

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

We've just rolled back to 2.18.1 for now.

**Comment by adrianthedev** [comment]
Please create a `dashboards` directory inside `app/avo` (`app/avo/dashboards`).

**Comment by koppen** [comment]
Man, I thought I had tried that - turns out I spelled it `app/avo/dashbaords` 🤦‍♂️

Did I miss some upgrade instructions at some point where that was noted?

**Comment by adrianthedev** [comment]
No worries. It happens to me every week 😛 

No, you haven't missed anything like that, but I'll update the upgrade guide anyways.
Not sure why it popped up now. We did push some zeitwerk updates in 2.19, but nothing related to dashboards. zeitwerk and properly auto-loading things is a tricky thing to get right (primarily because of my in-experience with autoloading).
