### ISSUE TITLE
Using select options in an action causes builds to crash.

### ISSUE THREAD

**Issue by holden** [avo-hq/avo#1675]
### Describe the bug

I have this avo action here:

```
class CreateRecord < Avo::BaseAction
  self.name = "Create record"
  self.visible = -> do
    if view == :show
      true
    else
      false
    end
  end

  field :genre_id, as: :select, options: ::Genre.try { all.map { |g| [g.name, g.id] } } # <----- this crashes even when wrapped in a try
  field :comment, as: :textarea
  field :value, as: :number
  field :condition, as: :select, enum: ::Record.conditions

  def handle(**args)
    models, fields, current_user, resource = args.values_at(:models, :fields, :current_user, :resource)
    #models, fields = args.values_at(:models, :fields)
    models.each do |model|
      # Do something with your models.
      record = model.records.build(
        artist_id: model.artist_id,
        label_id: model.label_id,
        user_id: current_user.id,
        record_format_id: model.record_format_id,
        comment: fields[:comment],
        value: fields[:value],
        genre_id: fields[:genre_id],
        condition: fields[:condition]
      )
      if record.save!
        succeed 'Yup'
        redirect_to avo.resources_record_path(record)
      else
        fail 'Error'
      end
    end
  end
end
```

Everything works fine in development. However when I try to deploy it to Fly.io my builds start crashing with 

```
Precompiling fails with:
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

  app/avo/actions/create_record.rb:12:in `map'
    field :genre_id, as: :select, options: Genre.all.map { |genre| [[genre.name](http://genre.name/), [genre.id](http://genre.id/)] }.to_h
  app/avo/actions/create_record.rb:12:in `<class:CreateRecord>'
    field :genre_id, as: :select, options: Genre.all.map { |genre| [[genre.name](http://genre.name/), [genre.id](http://genre.id/)] }.to_h
  app/avo/actions/create_record.rb:1:in `<main>'
    class CreateRecord < Avo::BaseAction
  app/avo/resources/price_resource.rb:8:in `<class:PriceResource>'
    action CreateRecord
  app/avo/resources/price_resource.rb:1:in `<main>'
    class PriceResource < Avo::BaseResource
...
(133 additional frame(s) were not displayed)
```

### Steps to Reproduce

I've tried re-writing the Genre.all method in several different ways but it doesn't change anything, if I remove this line, it builds without issue. 

### System configuration
**Avo version**:
2.29.1
**Rails version**:
7
**Ruby version**:
3.1.2
**License type**:

 - [ ] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by PedroAugustoRamalhoDuarte** [comment]
Hello, i have the same problem this week. The problem is that you are fetching select options in "load" time, change for this:

```ruby
field :genre_id, as: :select, options: ->(model:, resource:, view:, field:) do
  ::Genre.all.map { |g| [g.name, g.id] } # Maybe needs .to_h in the end
end,
```

I think you get more performance using pluck:
```ruby
::Genre.all.pluck(:name, :id)
```

Docs: https://docs.avohq.io/2.0/fields/select.html#computed-options

**Comment by adrianthedev** [comment]
Looking into it. I'll have a resolution for it in the next couple of days.

**Comment by holden** [comment]
Awesome thanks, @PedroAugustoRamalhoDuarte fix works for now. Thanks for that!

**Comment by adrianthedev** [comment]
Yeah @holden. What @PedroAugustoRamalhoDuarte suggested (thank you for the quick response) is the right fix for now.

The reason is that the way we declare fields on a resource/action is through a class method (`field`), which gets evaluated at boot time causing the crash. If you wrap it in a block, it will be evaluated on runtime, when more things are loaded and you don't trigger the crash.

In Avo 3 we have a plan to better support this use case.

Closing for now. Please feel free to reopen.
