### ISSUE TITLE
Reference used in model causes generator to stop

### ISSUE THREAD

**Issue by rafaqat** [avo-hq/avo#1713]
Using the following model and migration
```ruby
# This model represents the Sys_GRC_Assessment table in ServiceNow
class SysGrcAssessment < ApplicationRecord
  self.table_name = "sys_grc_assessment"

  # Field definitions
  attribute :refnumber, :string                        # Auto-generated unique number for the assessment record
  attribute :short_description, :string             # Brief summary or title for the assessment
  attribute :description, :string                   # Detailed description of the assessment
  attribute :assessment_type, :string               # Type of assessment (e.g. internal audit, external audit, compliance review)
  attribute :state, :string                         # Current status of the assessment (e.g. draft, in progress, closed)
  attribute :start_date, :datetime                  # Date the assessment began
  attribute :end_date, :datetime                    # Date the assessment ended
  # attribute :assessed_by, :reference, references: :user  # User or team responsible for performing the assessment
  # attribute :assigned_to, :reference, references: :user # User or team assigned to the assessment
  # attribute :related_items, :reference, polymorphic: true # Other items related to the assessment

  # Relationships
  has_many :sys_controls, foreign_key: :assessment, dependent: :destroy # Controls linked to the assessment
  has_many :sys_risks, through: :sys_controls                         # Risks linked to the assessment through controls
  has_many :sys_policies, foreign_key: :assessment, dependent: :destroy # Policies linked to the assessment

  # Validations
  validates :refnumber, presence: true, uniqueness: true        # Ensure the number is present and unique
  validates :short_description, presence: true               # Ensure the short description is present
  validates :description, presence: true                     # Ensure the description is present
  validates :assessment_type, presence: true                 # Ensure the assessment type is present
  validates :state, presence: true                           # Ensure the assessment state is present
  validates :start_date, presence: true                      # Ensure the start date is present
  validates :end_date, presence: true                        # Ensure the end date is present
   # validates :assessed_by, presence: true                     # Ensure the assessed_by field is present
   # validates :assigned_to, presence: true                     # Ensure the assigned_to field is present
   # validates :related_items, presence: true                   # Ensure the related_items field is present
end

Migration:
class CreateSysGrcAssessments < ActiveRecord::Migration[7.0]
  def change
    create_table :sys_grc_assessment do |t|
      t.string :refnumber, null: false
      t.string :short_description, null: false
      t.string :description, null: false
      t.string :assessment_type, null: false
      t.string :state, null: false
      t.datetime :start_date, null: false
      t.datetime :end_date, null: false
      t.references :assessed_by, foreign_key: { to_table: :user }, null: false
      t.references :assigned_to, foreign_key: { to_table: :user }, null: false
      t.references :related_items, polymorphic: true, null: false

      t.timestamps
    end

    add_index :sys_grc_assessment, :number, unique: true
  end
end
```

rails generate avo:resource sys_grc_assessment

causes this -> 
```
rails generate avo:resource sys_grc_assessment
/Users/rafaqatali/.gem/ruby/3.2.2/gems/activerecord-7.0.4.3/lib/active_record/type/adapter_specific_registry.rb:36:in `lookup': Unknown type :reference (ArgumentError)

          raise ArgumentError, "Unknown type #{symbol.inspect}"
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/activerecord-7.0.4.3/lib/active_record/type.rb:42:in `lookup'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/activerecord-7.0.4.3/lib/active_record/attributes.rb:216:in `attribute'
	from /Users/rafaqatali/work/railsapps/snow/app/models/sys_grc_assessment.rb:15:in `<class:SysGrcAssessment>'
	from /Users/rafaqatali/work/railsapps/snow/app/models/sys_grc_assessment.rb:2:in `<main>'
	from <internal:/Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/activesupport-7.0.4.3/lib/active_support/inflector/methods.rb:280:in `const_get'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/activesupport-7.0.4.3/lib/active_support/inflector/methods.rb:280:in `constantize'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/activesupport-7.0.4.3/lib/active_support/inflector/methods.rb:306:in `safe_constantize'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/activesupport-7.0.4.3/lib/active_support/core_ext/string/inflections.rb:87:in `safe_constantize'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/avo-2.30.2/lib/avo/base_resource.rb:224:in `model_class'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/avo-2.30.2/lib/avo/base_resource.rb:144:in `initialize'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/avo-2.30.2/lib/avo/dynamic_router.rb:20:in `new'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/avo-2.30.2/lib/avo/dynamic_router.rb:20:in `block (3 levels) in routes'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/avo-2.30.2/lib/avo/dynamic_router.rb:19:in `map'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/avo-2.30.2/lib/avo/dynamic_router.rb:19:in `block (2 levels) in routes'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:871:in `scope'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/avo-2.30.2/lib/avo/dynamic_router.rb:5:in `block in routes'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:625:in `instance_exec'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:625:in `block in with_default_scope'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:871:in `scope'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:624:in `with_default_scope'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:410:in `draw'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/avo-2.30.2/lib/avo/dynamic_router.rb:4:in `routes'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/avo-2.30.2/config/routes.rb:36:in `block (2 levels) in <main>'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:871:in `scope'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/avo-2.30.2/config/routes.rb:26:in `block in <main>'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:625:in `instance_exec'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:625:in `block in with_default_scope'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:871:in `scope'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:624:in `with_default_scope'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:410:in `draw'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/avo-2.30.2/config/routes.rb:1:in `<main>'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `load'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `block in load_paths'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `each'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `load_paths'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:24:in `reload!'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:38:in `block in updater'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/activesupport-7.0.4.3/lib/active_support/file_update_checker.rb:83:in `execute'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:13:in `execute'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/application/finisher.rb:158:in `block in <module:Finisher>'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'
	from /Users/rafaqatali/work/railsapps/snow/config/environment.rb:5:in `<main>'
	from <internal:/Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/application.rb:348:in `require_environment!'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/command/actions.rb:28:in `require_environment!'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/command/base.rb:87:in `perform'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/command.rb:48:in `invoke'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
	from <internal:/Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/rafaqatali/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/rafaqatali/.gem/ruby/3.2.2/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
(base) rafaqatali@rafaqats-MacBook-Pro snow % 
```

**Comment by adrianthedev** [comment]
This seems to be related to the `attribute` declarations. The code was generated by Chat-GPT and it might not be correct.

Closing for now.
