### ISSUE TITLE
Can't link to external links from sidebar

### ISSUE THREAD

**Issue by smathieu** [avo-hq/avo#1724]
### Describe the bug
I'm trying to add an external link to my sidebar, but Avo is raising an error.

### Steps to Reproduce

```
  config.main_menu = lambda {
    section "Documentation", icon: "bookmark" do
      link_to "External", "https://example.org"
    end
}
```

```
Started GET "/admin" for ::1 at 2023-05-02 11:35:25 -0700
   (3.8ms)  SELECT * FROM pg_type WHERE typname = 'category_subtype'
  ↳ app/models/application_record.rb:7:in `values_for_pg_enum'
   (1.6ms)  SELECT enumlabel FROM pg_enum WHERE enumtypid = 275639
  ↳ app/models/application_record.rb:11:in `values_for_pg_enum'
  AdminUser Load (1.4ms)  SELECT "admin_users".* FROM "admin_users" WHERE "admin_users"."id" = $1 ORDER BY "admin_users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
Processing by Avo::HomeController#index as HTML
  Rendering layout /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/layouts/avo/application.html.erb
  Rendering /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/home/index.html.erb within layouts/avo/application
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/home/_resources.html.erb (Duration: 0.1ms | Allocations: 152)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/home/_dashboards.html.erb (Duration: 0.0ms | Allocations: 13)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/home/_filters.html.erb (Duration: 0.0ms | Allocations: 13)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/home/_actions.html.erb (Duration: 0.0ms | Allocations: 13)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/home/_docs.html.erb (Duration: 0.0ms | Allocations: 13)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/home/index.html.erb within layouts/avo/application (Duration: 2.0ms | Allocations: 1965)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/partials/_javascript.html.erb (Duration: 0.1ms | Allocations: 115)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/partials/_branding.html.erb (Duration: 0.1ms | Allocations: 199)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/partials/_pre_head.html.erb (Duration: 0.0ms | Allocations: 13)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/partials/_head.html.erb (Duration: 0.0ms | Allocations: 13)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/partials/_logo.html.erb (Duration: 0.1ms | Allocations: 253)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/partials/_global_search.html.erb (Duration: 0.0ms | Allocations: 49)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/partials/_header.html.erb (Duration: 0.0ms | Allocations: 53)
  Rendered /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/avo/partials/_navbar.html.erb (Duration: 3.6ms | Allocations: 3640)
  Rendered layout /Users/smathieu/.gem/ruby/3.2.2/gems/avo-2.31.0/app/views/layouts/avo/application.html.erb (Duration: 17.4ms | Allocations: 20593)
Completed 500 Internal Server Error in 19ms (ActiveRecord: 0.0ms | Allocations: 23211)


  
ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
    27:         <%= render partial: "avo/partials/navbar" %>
    28:         <div data-sidebar-target="mainArea" class="content-area flex-1 flex pt-16 relative <%= 'sidebar-open' if @sidebar_open %>">
    29:           <div class="hidden lg:flex">
    30:             <%= render Avo::SidebarComponent.new sidebar_open: @sidebar_open %>
    31:           </div>
    32:           <div class="flex lg:hidden">
    33:             <%= render Avo::SidebarComponent.new sidebar_open: false, for_mobile: true %>
  
actionpack (7.0.4.3) lib/action_dispatch/http/url.rb:64:in `full_url_for'
actionpack (7.0.4.3) lib/action_dispatch/http/url.rb:54:in `url_for'
actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:334:in `block in <class:RouteSet>'
actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:846:in `url_for'
actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:271:in `call'
actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:214:in `call'
actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:327:in `block in define_url_helper'
actionpack (7.0.4.3) lib/action_dispatch/routing/routes_proxy.rb:45:in `root_url'
avo (2.31.0) lib/avo/app.rb:43:in `root_path'
avo (2.31.0) app/components/avo/sidebar/link_component.rb:20:in `is_external?'
avo (2.31.0) app/components/avo/sidebar/link_component.rb:27:in `link_method'
avo (2.31.0) app/components/avo/sidebar/link_component.html.erb:2:in `call'
view_component (3.0.0) lib/view_component/compiler.rb:115:in `render_template_for'
view_component (3.0.0) lib/view_component/base.rb:105:in `render_in'
actionview (7.0.4.3) lib/action_view/helpers/rendering_helper.rb:42:in `render'
view_component (3.0.0) lib/view_component/base.rb:164:in `render'
avo (2.31.0) app/components/avo/sidebar/item_switcher_component.html.erb:2:in `call'
view_component (3.0.0) lib/view_component/compiler.rb:115:in `render_template_for'
view_component (3.0.0) lib/view_component/base.rb:105:in `render_in'
actionview (7.0.4.3) lib/action_view/helpers/rendering_helper.rb:42:in `render'
view_component (3.0.0) lib/view_component/base.rb:164:in `render'
avo (2.31.0) app/components/avo/sidebar/section_component.html.erb:12:in `block in call'
avo (2.31.0) app/components/avo/sidebar/section_component.html.erb:11:in `each'
avo (2.31.0) app/components/avo/sidebar/section_component.html.erb:11:in `call'
view_component (3.0.0) lib/view_component/compiler.rb:115:in `render_template_for'
view_component (3.0.0) lib/view_component/base.rb:105:in `render_in'
actionview (7.0.4.3) lib/action_view/helpers/rendering_helper.rb:42:in `render'
view_component (3.0.0) lib/view_component/base.rb:164:in `render'
avo (2.31.0) app/components/avo/sidebar/item_switcher_component.html.erb:11:in `call'
view_component (3.0.0) lib/view_component/compiler.rb:115:in `render_template_for'
view_component (3.0.0) lib/view_component/base.rb:105:in `render_in'
actionview (7.0.4.3) lib/action_view/helpers/rendering_helper.rb:42:in `render'
view_component (3.0.0) lib/view_component/base.rb:164:in `render'
avo (2.31.0) app/components/avo/sidebar_component.html.erb:18:in `block in call'
avo (2.31.0) app/components/avo/sidebar_component.html.erb:17:in `each'
avo (2.31.0) app/components/avo/sidebar_component.html.erb:17:in `call'
view_component (3.0.0) lib/view_component/compiler.rb:115:in `render_template_for'
view_component (3.0.0) lib/view_component/base.rb:105:in `render_in'
actionview (7.0.4.3) lib/action_view/helpers/rendering_helper.rb:42:in `render'
avo (2.31.0) app/views/layouts/avo/application.html.erb:30
actionview (7.0.4.3) lib/action_view/base.rb:244:in `public_send'
actionview (7.0.4.3) lib/action_view/base.rb:244:in `_run'
actionview (7.0.4.3) lib/action_view/template.rb:157:in `block in render'
activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.4.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.4.3) lib/action_view/template.rb:361:in `instrument_render_template'
actionview (7.0.4.3) lib/action_view/template.rb:155:in `render'
actionview (7.0.4.3) lib/action_view/renderer/template_renderer.rb:76:in `block in render_with_layout'
activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.4.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.4.3) lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
actionview (7.0.4.3) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
actionview (7.0.4.3) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (7.0.4.3) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (7.0.4.3) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (7.0.4.3) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (7.0.4.3) lib/action_view/base.rb:270:in `in_rendering_context'
actionview (7.0.4.3) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (7.0.4.3) lib/action_controller/metal/streaming.rb:216:in `_render_template'
actionview (7.0.4.3) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (7.0.4.3) lib/action_controller/metal/rendering.rb:46:in `render_to_body'
actionpack (7.0.4.3) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (7.0.4.3) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (7.0.4.3) lib/action_controller/metal/rendering.rb:30:in `render'
actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:22:in `block (2 levels) in render'
/Users/smathieu/.rubies/ruby-3.2.2/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
activesupport (7.0.4.3) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:22:in `block in render'
actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:91:in `cleanup_view_runtime'
activerecord (7.0.4.3) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:21:in `render'
meta-tags (2.18.0) lib/meta_tags/controller_helper.rb:22:in `render'
avo (2.31.0) app/controllers/avo/application_controller.rb:68:in `render'
actionpack (7.0.4.3) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (7.0.4.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
<internal:kernel>:90:in `tap'
actionpack (7.0.4.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (7.0.4.3) lib/abstract_controller/base.rb:215:in `process_action'
actionpack (7.0.4.3) lib/action_controller/metal/rendering.rb:53:in `process_action'
actionpack (7.0.4.3) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
activesupport (7.0.4.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
i18n (1.12.0) lib/i18n.rb:322:in `with_locale'
avo (2.31.0) app/controllers/avo/application_controller.rb:325:in `set_avo_locale'
activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
actiontext (7.0.4.3) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (7.0.4.3) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `instance_exec'
activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
sentry-rails (5.8.0) lib/sentry/rails/controller_transaction.rb:28:in `block in sentry_around_action'
sentry-ruby (5.8.0) lib/sentry/hub.rb:100:in `with_child_span'
sentry-ruby (5.8.0) lib/sentry-ruby.rb:446:in `with_child_span'
sentry-rails (5.8.0) lib/sentry/rails/controller_transaction.rb:14:in `sentry_around_action'
activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
activesupport (7.0.4.3) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.4.3) lib/abstract_controller/callbacks.rb:233:in `process_action'
actionpack (7.0.4.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.4.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
actionpack (7.0.4.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
activerecord (7.0.4.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (7.0.4.3) lib/abstract_controller/base.rb:151:in `process'
actionview (7.0.4.3) lib/action_view/rendering.rb:39:in `process'
actionpack (7.0.4.3) lib/action_controller/metal.rb:188:in `dispatch'
actionpack (7.0.4.3) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
railties (7.0.4.3) lib/rails/engine.rb:530:in `call'
railties (7.0.4.3) lib/rails/railtie.rb:226:in `public_send'
railties (7.0.4.3) lib/rails/railtie.rb:226:in `method_missing'
actionpack (7.0.4.3) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (7.0.4.3) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
omniauth (2.1.1) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.1) lib/omniauth/strategy.rb:169:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/static.rb:23:in `call'
warden-jwt_auth (0.8.0) lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
warden-jwt_auth (0.8.0) lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
rack (2.2.7) lib/rack/builder.rb:244:in `call'
warden-jwt_auth (0.8.0) lib/warden/jwt_auth/middleware.rb:22:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.7) lib/rack/static.rb:161:in `call'
rack (2.2.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.7) lib/rack/etag.rb:27:in `call'
rack (2.2.7) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.7) lib/rack/head.rb:12:in `call'
actionpack (7.0.4.3) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
actionpack (7.0.4.3) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack (2.2.7) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.7) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/cookies.rb:704:in `call'
activerecord (7.0.4.3) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.4.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.4.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
sentry-rails (5.8.0) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
sentry-ruby (5.8.0) lib/sentry/rack/capture_exceptions.rb:28:in `block (2 levels) in call'
sentry-ruby (5.8.0) lib/sentry/hub.rb:220:in `with_session_tracking'
sentry-ruby (5.8.0) lib/sentry-ruby.rb:375:in `with_session_tracking'
sentry-ruby (5.8.0) lib/sentry/rack/capture_exceptions.rb:19:in `block in call'
sentry-ruby (5.8.0) lib/sentry/hub.rb:59:in `with_scope'
sentry-ruby (5.8.0) lib/sentry-ruby.rb:355:in `with_scope'
sentry-ruby (5.8.0) lib/sentry/rack/capture_exceptions.rb:18:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.4.3) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.4.3) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.4.3) lib/rails/rack/logger.rb:25:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.7) lib/rack/method_override.rb:24:in `call'
rack (2.2.7) lib/rack/runtime.rb:22:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
actionpack (7.0.4.3) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.7) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.4.3) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
railties (7.0.4.3) lib/rails/engine.rb:530:in `call'
puma (6.2.1) lib/puma/configuration.rb:270:in `call'
puma (6.2.1) lib/puma/request.rb:98:in `block in handle_request'
puma (6.2.1) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (6.2.1) lib/puma/request.rb:97:in `handle_request'
puma (6.2.1) lib/puma/server.rb:431:in `process_client'
puma (6.2.1) lib/puma/server.rb:233:in `block in run'
puma (6.2.1) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started POST "/__web_console/repl_sessions/12752f5d4aab7dc9743a5463b13aae69/trace" for ::1 at 2023-05-02 11:35:32 -0700
Started POST "/__web_console/repl_sessions/12752f5d4aab7dc9743a5463b13aae69/trace" for ::1 at 2023-05-02 11:35:34 -0700
Started POST "/__web_console/repl_sessions/12752f5d4aab7dc9743a5463b13aae69/trace" for ::1 at 2023-05-02 11:35:38 -0700

```

### Expected behavior & Actual behavior
Just link.

### System configuration
**Avo version**:
2.31.0

**Rails version**:
7.0.4.3

**Ruby version**:
3.2.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Hey @smathieu. Thanks for writing.

I can't seem to reproduce this error. I tried external paths "https://google.com", I tried `localhost` path, `lvh.me`, relative path `/hey`, but can't seem to get that error with `link_to` in menus.

I know I've seen that error before from Rails, but I'm unsure how to reproduce it here.

Can you please post the exact line of code you are using?

**Comment by smathieu** [comment]
Thanks for looking into it. Turns out this wan't an Avo bug, but a confusing rails error message. I had included `Rails.application.routes.url_helpers` in the lambda to link to other resources, but that overrode some routes in Avo.

I'm going to close this.

**Comment by adrianthedev** [comment]
Got it!
Thanks for letting me know!✌️
