### ISSUE TITLE
Avo 2.32 introduces dependency on dalli

### ISSUE THREAD

**Issue by fastjames** [avo-hq/avo#1731]
### Describe the bug
After upgrading our rails application to avo 2.32.0 this morning, the next heroku deploy attempt failed with the following message:

```
-----> Preparing app for Rails asset pipeline

       Running: rake assets:precompile

       You don't have dalli installed in your application. Please add it to your Gemfile and run bundle install

       rake aborted!

       LoadError: cannot load such file -- dalli

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/cache/mem_cache_store.rb:4:in `<main>'

       <internal:/tmp/build_2353c68c/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'

       <internal:/tmp/build_2353c68c/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/avo-2.32.0/lib/avo/app.rb:44:in `get_cache_store'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/avo-2.32.0/lib/avo/app.rb:34:in `boot'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/avo-2.32.0/lib/avo/engine.rb:23:in `block in <class:Engine>'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:92:in `block in execute_hook'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:76:in `block in run_load_hooks'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:75:in `each'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:75:in `run_load_hooks'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/application/finisher.rb:87:in `block in <module:Finisher>'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'

       /tmp/build_2353c68c/config/environment.rb:5:in `<main>'

       <internal:/tmp/build_2353c68c/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'

       <internal:/tmp/build_2353c68c/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:348:in `require_environment!'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:511:in `block in run_tasks_blocks'

       /tmp/build_2353c68c/vendor/bundle/ruby/3.2.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'

       Tasks: TOP => environment

       (See full trace by running task with --trace)

 !

 !     Precompiling assets failed.
```

This is unexpected because we don't use memcached in this application. I noticed that 2.32.0 included https://github.com/avo-hq/avo/commit/714fb6d16e920012f1973cfe32ecfde1a41ced0d so I wonder if that altered the logic just enough to cause our application to fall back to memcached?

### Steps to Reproduce
1. Add this configuration '...'
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

### Expected behavior & Actual behavior
I expected that the rails application would build and deploy as normal, but instead it failed with an error about missing the dalli gem (which we should not need).

### System configuration
**Avo version**: 2.32.0

**Rails version**: 7.0.4.3

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by fastjames** [comment]
Looking at that commit more closely, this line
https://github.com/avo-hq/avo/commit/714fb6d16e920012f1973cfe32ecfde1a41ced0d#diff-97c6e3d3650b454f6e5b88879082356a77622820bced48fa9b4b300789fb7309R44
refers to the `ActiveSupport::Cache::MemCacheStore` directly. Would doing so call code in that class, and could that be where the dalli dependency is introduced?

**Comment by fastjames** [comment]
I was able to replicate the problem in a local rails console:

```
❯ bin/rails c
Loading development environment (Rails 7.0.4.3)
[1] pry(main)> Rails.cache.class
=> ActiveSupport::Cache::NullStore
[2] pry(main)> Rails.cache.class.to_s
=> "ActiveSupport::Cache::NullStore"
[3] pry(main)> ActiveSupport::Cache::MemCacheStore
You don't have dalli installed in your application. Please add it to your Gemfile and run bundle install
LoadError: cannot load such file -- dalli
from /Users/foobar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
[4] pry(main)>
```
