### ISSUE TITLE
Graceful handling of user error in giving resource a plural name

### ISSUE THREAD

**Issue by brandondrew** [avo-hq/avo#1752]
### Describe the bug

If I accidentally name a resource with a plural name, it appears to work fine at first, but the next command gives me a Zeitwerk error:

```
brandon@Air portal % bin/rails generate avo:resource regions
Avo community 2.32.5
      create  app/avo/resources/region_resource.rb
      create  app/controllers/avo/regions_controller.rb
brandon@Air portal % bin/rails generate avo:resource reappointment
/Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded': expected file /Users/brandon/Code/Rails/portal/app/avo/resources/region_resource.rb to define constant RegionResource, but didn't (Zeitwerk::NameError)

      raise Zeitwerk::NameError.new(msg, cref.last)
      ^^^^^
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:31:in `require'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `cget'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `each'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `ls'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:68:in `eager_load_dir'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/avo-2.32.5/lib/avo/app.rb:27:in `eager_load'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/avo-2.32.5/lib/avo/dynamic_router.rb:9:in `block (2 levels) in routes'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:871:in `scope'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/avo-2.32.5/lib/avo/dynamic_router.rb:5:in `block in routes'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:625:in `instance_exec'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:625:in `block in with_default_scope'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:871:in `scope'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:624:in `with_default_scope'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:410:in `draw'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/avo-2.32.5/lib/avo/dynamic_router.rb:4:in `routes'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/avo-2.32.5/config/routes.rb:36:in `block (2 levels) in <main>'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:871:in `scope'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/avo-2.32.5/config/routes.rb:26:in `block in <main>'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:625:in `instance_exec'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:625:in `block in with_default_scope'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:871:in `scope'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/mapper.rb:624:in `with_default_scope'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.4.3/lib/action_dispatch/routing/route_set.rb:410:in `draw'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/avo-2.32.5/config/routes.rb:1:in `<main>'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `load'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `block in load_paths'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `each'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:50:in `load_paths'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:24:in `reload!'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:38:in `block in updater'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/file_update_checker.rb:83:in `execute'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/routes_reloader.rb:13:in `execute'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application/finisher.rb:158:in `block in <module:Finisher>'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'
        from /Users/brandon/Code/Rails/portal/config/environment.rb:5:in `<main>'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:348:in `require_environment!'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/actions.rb:28:in `require_environment!'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/base.rb:87:in `perform'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command.rb:48:in `invoke'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/brandon/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
brandon@Air portal % s
```

Clearly the plural name was a user error, but it would be preferable if the generator 
- warned me that a plural name is a problem, or
- corrected the name, or
- both.

### Steps to Reproduce
1. generate a resource with a plural name
2. do anything else which loads your Rails app
3. See the stack trace

### Expected behavior & Actual behavior

A warning, at least, after the plural name would be helpful.

### System configuration
**Avo version**: 2.32.5

**Rails version**: 7.0.4.3

**Ruby version**: 3.2.2

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Additional context

As far as I know this will happen with any plural name given.  If you can't reproduce it, I'll try to figure out what might be different about my setup.

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
That's a good spot! Yeah, that can be automated to improve the user experience.

Would you be available to send in a PR?

**Comment by brandondrew** [comment]
Possibly... although it might be a little while

**Comment by adrianthedev** [comment]
It's unfortunate that that's happening, but it's a very minor thing which we won't fix.
