### ISSUE TITLE
Can't use "format_using" on a file field 

### ISSUE THREAD

**Issue by konung** [avo-hq/avo#1763]
### Describe the bug

Hi

I have a file field that tends to be quite long. I want to truncate the filename on an index action. Running into error

```ruby
field :original_file, as: :file, accept: ".pdf", format_using: ->(value) { value&.filename.to_s.truncate(25) }
```

I also tried this to no avail. 
https://docs.avohq.io/2.0/faq.html#get-access-to-the-actionview-helper-methods

### System configuration
**Avo version**:
2.33.0
**Rails version**:
7.0.4.3
**Ruby version**:
3.2.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [X] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [X] Low urgency (It can wait. I just wanted you to know about it.)
 
 ### Error trace
 
```ruby
 ActionView::Template::Error (undefined method `attached?' for "Long Truncated Filena...":String):
     1: <%= render Avo::TurboFrameWrapperComponent.new(params[:turbo_frame]) do %>
     2:   <%= render Avo::Views::ResourceIndexComponent.new(
     3:       resource: @resource,
     4:       resources: @resources,
     5:       models: @models,

 avo (2.33.0) app/components/avo/fields/file_field/index_component.rb:9:in `has_image_tag?'
 avo (2.33.0) app/components/avo/fields/file_field/index_component.rb:5:in `flush?'
 avo (2.33.0) app/components/avo/fields/file_field/index_component.html.erb:1:in `call'
 view_component (3.0.0) lib/view_component/compiler.rb:115:in `render_template_for'
 view_component (3.0.0) lib/view_component/base.rb:105:in `render_in'
 actionview (7.0.4.3) lib/action_view/helpers/rendering_helper.rb:42:in `render'
 view_component (3.0.0) lib/view_component/base.rb:164:in `render'
 avo (2.33.0) app/components/avo/index/table_row_component.html.erb:20:in `block in call'
 avo (2.33.0) app/components/avo/index/table_row_component.html.erb:19:in `each'
 avo (2.33.0) app/components/avo/index/table_row_component.html.erb:19:in `each_with_index'
 avo (2.33.0) app/components/avo/index/table_row_component.html.erb:19:in `call'
 view_component (3.0.0) lib/view_component/compiler.rb:115:in `render_template_for'
 view_component (3.0.0) lib/view_component/base.rb:105:in `render_in'
 actionview (7.0.4.3) lib/action_view/helpers/rendering_helper.rb:42:in `render'
 view_component (3.0.0) lib/view_component/base.rb:164:in `render'
 avo (2.33.0) app/components/avo/index/resource_table_component.html.erb:43:in `block (2 levels) in call'
 actionview (7.0.4.3) lib/action_view/helpers/cache_helper.rb:175:in `cache'
 actionview (7.0.4.3) lib/action_view/helpers/cache_helper.rb:217:in `cache_if'
 avo (2.33.0) app/components/avo/index/resource_table_component.html.erb:42:in `block in call'
 avo (2.33.0) app/components/avo/index/resource_table_component.html.erb:41:in `each'
 avo (2.33.0) app/components/avo/index/resource_table_component.html.erb:41:in `each_with_index'
 avo (2.33.0) app/components/avo/index/resource_table_component.html.erb:41:in `call'
 view_component (3.0.0) lib/view_component/compiler.rb:115:in `render_template_for'
 view_component (3.0.0) lib/view_component/base.rb:105:in `render_in'
 actionview (7.0.4.3) lib/action_view/helpers/rendering_helper.rb:42:in `render'
 view_component (3.0.0) lib/view_component/base.rb:164:in `render'
 avo (2.33.0) app/components/avo/views/resource_index_component.html.erb:61:in `block (3 levels) in call'
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:45:in `capture'
 view_component (3.0.0) lib/view_component/slot.rb:67:in `to_s'
 actionview (7.0.4.3) lib/action_view/buffers.rb:29:in `<<'
 avo (2.33.0) app/components/avo/panel_component.html.erb:31:in `block in call'
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:45:in `capture'
 actionview (7.0.4.3) lib/action_view/helpers/tag_helper.rb:371:in `content_tag'
 avo (2.33.0) app/components/avo/panel_component.html.erb:1:in `call'
 view_component (3.0.0) lib/view_component/compiler.rb:115:in `render_template_for'
 view_component (3.0.0) lib/view_component/base.rb:105:in `render_in'
 actionview (7.0.4.3) lib/action_view/helpers/rendering_helper.rb:42:in `render'
 view_component (3.0.0) lib/view_component/base.rb:164:in `render'
 avo (2.33.0) app/components/avo/views/resource_index_component.html.erb:7:in `block in call'
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:45:in `capture'
 actionview (7.0.4.3) lib/action_view/helpers/tag_helper.rb:371:in `content_tag'
 avo (2.33.0) app/components/avo/views/resource_index_component.html.erb:1:in `call'
 view_component (3.0.0) lib/view_component/compiler.rb:115:in `render_template_for'
 view_component (3.0.0) lib/view_component/base.rb:105:in `render_in'
 actionview (7.0.4.3) lib/action_view/helpers/rendering_helper.rb:42:in `render'
 avo (2.33.0) app/views/avo/base/index.html.erb:2
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
 actionview (7.0.4.3) lib/action_view/helpers/capture_helper.rb:45:in `capture'
 view_component (3.0.0) lib/view_component/base.rb:234:in `content'
 avo (2.33.0) app/components/avo/turbo_frame_wrapper_component.html.erb:9:in `call'
 view_component (3.0.0) lib/view_component/compiler.rb:115:in `render_template_for'
 view_component (3.0.0) lib/view_component/base.rb:105:in `render_in'
 actionview (7.0.4.3) lib/action_view/helpers/rendering_helper.rb:42:in `render'
 avo (2.33.0) app/views/avo/base/index.html.erb:1
 actionview (7.0.4.3) lib/action_view/base.rb:244:in `public_send'
 actionview (7.0.4.3) lib/action_view/base.rb:244:in `_run'
 actionview (7.0.4.3) lib/action_view/template.rb:157:in `block in render'
 activesupport (7.0.4.3) lib/active_support/notifications.rb:208:in `instrument'
 actionview (7.0.4.3) lib/action_view/template.rb:361:in `instrument_render_template'
 actionview (7.0.4.3) lib/action_view/template.rb:155:in `render'
 actionview (7.0.4.3) lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
 activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `block in instrument'
 activesupport (7.0.4.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'
 actionview (7.0.4.3) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
 actionview (7.0.4.3) lib/action_view/renderer/template_renderer.rb:75:in `block in render_with_layout'
 activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `block in instrument'
 activesupport (7.0.4.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'
 actionview (7.0.4.3) lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
 actionview (7.0.4.3) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
 actionview (7.0.4.3) lib/action_view/renderer/template_renderer.rb:11:in `render'
 actionview (7.0.4.3) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
 actionview (7.0.4.3) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
 actionview (7.0.4.3) lib/action_view/rendering.rb:117:in `block in _render_template'
 actionview (7.0.4.3) lib/action_view/base.rb:270:in `in_rendering_context'
 actionview (7.0.4.3) lib/action_view/rendering.rb:116:in `_render_template'
 actionpack (7.0.4.3) lib/action_controller/metal/streaming.rb:216:in `_render_template'
 actionview (7.0.4.3) lib/action_view/rendering.rb:103:in `render_to_body'
 actionpack (7.0.4.3) lib/action_controller/metal/rendering.rb:46:in `render_to_body'
 actionpack (7.0.4.3) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
 actionpack (7.0.4.3) lib/abstract_controller/rendering.rb:25:in `render'
 actionpack (7.0.4.3) lib/action_controller/metal/rendering.rb:30:in `render'
 actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:22:in `block (2 levels) in render'
 /usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
 activesupport (7.0.4.3) lib/active_support/core_ext/benchmark.rb:14:in `ms'
 actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:22:in `block in render'
 actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:91:in `cleanup_view_runtime'
 activerecord (7.0.4.3) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
 actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:21:in `render'
 meta-tags (2.18.0) lib/meta_tags/controller_helper.rb:22:in `render'
 trailblazer-rails (2.4.3) lib/trailblazer/rails/cell.rb:4:in `render'
 avo (2.33.0) app/controllers/avo/application_controller.rb:68:in `render'
 actionpack (7.0.4.3) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
 actionpack (7.0.4.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
 <internal:kernel>:90:in `tap'
 actionpack (7.0.4.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 actionpack (7.0.4.3) lib/abstract_controller/base.rb:215:in `process_action'
 actionpack (7.0.4.3) lib/action_controller/metal/rendering.rb:53:in `process_action'
 actionpack (7.0.4.3) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
 activesupport (7.0.4.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
 i18n (1.13.0) lib/i18n.rb:322:in `with_locale'
 avo (2.33.0) app/controllers/avo/application_controller.rb:329:in `set_avo_locale'
 activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
 actiontext (7.0.4.3) lib/action_text/rendering.rb:20:in `with_renderer'
 actiontext (7.0.4.3) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
 activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `instance_exec'
 activesupport (7.0.4.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
 activesupport (7.0.4.3) lib/active_support/callbacks.rb:138:in `run_callbacks'
 actionpack (7.0.4.3) lib/abstract_controller/callbacks.rb:233:in `process_action'
 actionpack (7.0.4.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
 actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
 activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `block in instrument'
 activesupport (7.0.4.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 activesupport (7.0.4.3) lib/active_support/notifications.rb:206:in `instrument'
 actionpack (7.0.4.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
 actionpack (7.0.4.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
 activerecord (7.0.4.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 actionpack (7.0.4.3) lib/abstract_controller/base.rb:151:in `process'
 actionview (7.0.4.3) lib/action_view/rendering.rb:39:in `process'
 actionpack (7.0.4.3) lib/action_controller/metal.rb:188:in `dispatch'
 actionpack (7.0.4.3) lib/action_controller/metal.rb:251:in `dispatch'
 actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
 actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
 actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
 actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `each'
 actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `serve'
 actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
 railties (7.0.4.3) lib/rails/engine.rb:530:in `call'
 railties (7.0.4.3) lib/rails/railtie.rb:226:in `public_send'
 railties (7.0.4.3) lib/rails/railtie.rb:226:in `method_missing'
 actionpack (7.0.4.3) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
 actionpack (7.0.4.3) lib/action_dispatch/routing/mapper.rb:48:in `serve'
 actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
 actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `each'
 actionpack (7.0.4.3) lib/action_dispatch/journey/router.rb:32:in `serve'
 actionpack (7.0.4.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/static.rb:23:in `call'
 omniauth (2.1.1) lib/omniauth/strategy.rb:202:in `call!'
 omniauth (2.1.1) lib/omniauth/strategy.rb:169:in `call'
 rack (2.2.7) lib/rack/static.rb:161:in `call'
 warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
 warden (1.2.9) lib/warden/manager.rb:34:in `catch'
 warden (1.2.9) lib/warden/manager.rb:34:in `call'
 rack (2.2.7) lib/rack/tempfile_reaper.rb:15:in `call'
 rack (2.2.7) lib/rack/etag.rb:27:in `call'
 rack (2.2.7) lib/rack/conditional_get.rb:27:in `call'
 rack (2.2.7) lib/rack/head.rb:12:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
 rack (2.2.7) lib/rack/session/abstract/id.rb:266:in `context'
 rack (2.2.7) lib/rack/session/abstract/id.rb:260:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/cookies.rb:704:in `call'
 activerecord (7.0.4.3) lib/active_record/migration.rb:603:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 activesupport (7.0.4.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
 web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
 web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
 web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
 web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
 railties (7.0.4.3) lib/rails/rack/logger.rb:40:in `call_app'
 railties (7.0.4.3) lib/rails/rack/logger.rb:25:in `block in call'
 activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:99:in `block in tagged'
 activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:37:in `tagged'
 activesupport (7.0.4.3) lib/active_support/tagged_logging.rb:99:in `tagged'
 railties (7.0.4.3) lib/rails/rack/logger.rb:25:in `call'
 sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
 rack (2.2.7) lib/rack/method_override.rb:24:in `call'
 rack (2.2.7) lib/rack/runtime.rb:22:in `call'
 activesupport (7.0.4.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/static.rb:23:in `call'
 rack (2.2.7) lib/rack/sendfile.rb:110:in `call'
 actionpack (7.0.4.3) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
 rack-mini-profiler (3.1.0) lib/mini_profiler.rb:413:in `call'
 railties (7.0.4.3) lib/rails/engine.rb:530:in `call'
 puma (6.2.2) lib/puma/configuration.rb:270:in `call'
 puma (6.2.2) lib/puma/request.rb:98:in `block in handle_request'
 puma (6.2.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
 puma (6.2.2) lib/puma/request.rb:97:in `handle_request'
 puma (6.2.2) lib/puma/server.rb:431:in `process_client'
 puma (6.2.2) lib/puma/server.rb:233:in `block in run'
 puma (6.2.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
 
```

**Comment by konung** [comment]
Thank you, Paul 

I figured out a similar solution, but thought that I might be missing something . 

I thought I would bring it up as a bug, because `format_using`,  shouldn't be modifying ActiveStorage::Attached::One instance. At least that was my “the least surprise” expectation based on the docs and naming. It should only be concerned with the displaying/decorating ? Modifying instance seems to be counter to that? 

Perhaps there should be a “display_filename_format” option for `field :file`?

Just my  2🪙 :)

**Comment by Paul-Bob** [comment]
Got it, from that perspective, I can understand the "surprise." The `value` passed to `format_using` always represents the DB value. When discussing the `displaying/decorating` of a file field, there may be some controversy. In your specific use case, it would make sense for `value` to refer to the `filename`, while in other scenarios, it might make sense for `value` to refer to the `blob` or the `file_url`. This is why keeping it general and consistently passing the DB value makes it reusable for most use cases. However, I can comprehend that it may seem counterintuitive for file fields.

Regarding the `display_filename_format` option, I agree that it would be more intuitive to use. What do you think, @adrianthedev?

I believe we can achieve something like this: `filename: -> { record.file.filename.to_s.truncate(25) }`. A block that receives the `record` the `resource` and allows to format the filename easily.

**Comment by konung** [comment]
Totally get where you are coming from. Perhaps my example + your explanation in the docs, would solve this well enough 😄 and then there is no need for a change in API.

**Comment by adrianthedev** [comment]
I think this will fix it:

```ruby
field :original_file, as: :file, accept: ".pdf", format_using: ->(value) do
  value.attachment.filename = 'whatever you like'
  value
end
```

The explanation here is that the `value` is not the URL of the file or the filename, but the attachment record `ActiveStorage::Attached::One`. We just go and manipulate the filename that's available to us there.

Does that make sense?

Closing for now. Please feel free to reopen if it's still an issue.
