### ISSUE TITLE
undefined method hydrate for nil class: has_many through failing

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#1907]
### Context
I have a video which has_many dancers through dancer_videos. In the show view I get an error `undefined method hydrate for nil class`

### System configuration
**Avo version**:
2.34.5

**Rails version**:
7.0.6

**Ruby version**:
3.1.4
**License type**

 - [ ] Community
 - [X] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

### Screenshots or screen recordings

```ruby
class VideoResource < Avo::BaseResource
  self.title = :title
  self.includes = [:channel, :song, :event, :video_score, :dancers, :dancer_videos]
  self.search_query = -> { scope.search(params[:q]) }
  self.resolve_query_scope = ->(model_class:) do
    model_class.trending_1
  end

  self.find_record_method = ->(model_class:, id:, params:) {
    (!id.is_a?(Array) && id.to_i == 0) ? model_class.find_by(youtube_id: id) : model_class.find(id)
  }

  grid do
    cover :thumbnail, as: :file, is_image: true
    title :youtube_id, as: :text do
      model.title
    end
    body :description, as: :text do
      model.description
    end
  end

  field :id, as: :id
  field :link, as: :text do |video|
    link_to "Video", main_app.watch_path(v: video.youtube_id), target: "_blank", rel: "noopener"
  end
  field :link, as: :text do |video|
    link_to "Youtube", "https://www.youtube.com/watch?v=#{video.youtube_id}", target: "_blank", rel: "noopener"
  end
  field :thumbnail, as: :file, is_image: true
  field :song, as: :belongs_to
  field :channel, as: :belongs_to
  field :hidden, as: :boolean
  field :featured, as: :boolean
  field :event, as: :belongs_to
  field :score_1, as: :number do |model|
    format("%.3f", model.video_score.score_1)
  end
  field :score_2, as: :number do |model|
    format("%.3f", model.video_score.score_2)
  end
  field :score_3, as: :number do |model|
    format("%.3f", model.video_score.score_3)
  end
  field :score_4, as: :number do |model|
    format("%.3f", model.video_score.score_4)
  end
  field :score_5, as: :number do |model|
    format("%.3f", model.video_score.score_5)
  end
  field :metadata, as: :code, language: "javascript", only_on: :edit
  field :metadata, as: :code, language: "javascript" do |model|
    if model.metadata.present?
      JSON.pretty_generate(model.metadata.as_json)
    end
  end
  field :upload_date, as: :date
  field :metadata_updated_at, as: :date_time, hide_on: [:new, :edit, :index]
  field :dancer_videos, as: :has_many
  field :dancers, as: :has_many, through: :dancer_videos
  field :created_at, as: :date_time, hide_on: [:new, :edit, :index]
  field :updated_at, as: :date_time, hide_on: [:new, :edit, :index]

  action ToggleHidden
  action ToggleFeatured

  filter FeaturedFilter
  filter HiddenFilter
end
```

```
web    | Completed 500 Internal Server Error in 218ms (ActiveRecord: 72.3ms | Allocations: 9294)
web    |
web    |
web    |
web    | NoMethodError (undefined method `hydrate' for nil:NilClass):
web    |
web    | avo (2.34.5) app/controllers/avo/application_controller.rb:127:in `set_related_resource'
web    | activesupport (7.0.6) lib/active_support/callbacks.rb:400:in `block in make_lambda'
web    | activesupport (7.0.6) lib/active_support/callbacks.rb:180:in `block (2 levels) in halting_and_conditional'
web    | actionpack (7.0.6) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
web    | activesupport (7.0.6) lib/active_support/callbacks.rb:181:in `block in halting_and_conditional'
web    | activesupport (7.0.6) lib/active_support/callbacks.rb:595:in `block in invoke_before'
web    | activesupport (7.0.6) lib/active_support/callbacks.rb:595:in `each'
web    | activesupport (7.0.6) lib/active_support/callbacks.rb:595:in `invoke_before'
web    | activesupport (7.0.6) lib/active_support/callbacks.rb:116:in `block in run_callbacks'
web    | i18n (1.14.1) lib/i18n.rb:322:in `with_locale'
web    | avo (2.34.5) app/controllers/avo/application_controller.rb:329:in `set_avo_locale'
web    | activesupport (7.0.6) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
web    | actiontext (7.0.6) lib/action_text/rendering.rb:20:in `with_renderer'
web    | actiontext (7.0.6) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
web    | activesupport (7.0.6) lib/active_support/callbacks.rb:127:in `instance_exec'
web    | activesupport (7.0.6) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
web    | sentry-rails (5.9.0) lib/sentry/rails/controller_transaction.rb:28:in `block in sentry_around_action'
web    | sentry-ruby (5.9.0) lib/sentry/hub.rb:102:in `with_child_span'
```
![image](https://github.com/avo-hq/avo/assets/48605824/e7a12e6a-889d-43d7-8fca-e8cbee0f94bc)

**Comment by adrianthedev** [comment]
Was this fixed? Can you please tell us a bit about the issue so others know about it when they land here?

Thank you Justin!

**Comment by jmarsh24** [comment]
@adrianthedev 

Yes I fixed the issue. I realized that I had not added a dancer_video_resource. So the loading association wasn't showing up. I had integrated avo later on in my project and forgot some resources. 

The error here could be improved as I think it might be very common for somebody to run into it, when I googled nothing came up. Perhaps we can also add a suggestion that maybe the resource is missing?

**Comment by adrianthedev** [comment]
I agree! I think we should specify something along the lines that "Avo failed to find a resource for X association".
I can't remember right now if we fixed it in Avo 3 or we have it on the roadmap.

Thanks for getting back to us with the answer.

**Comment by adrianthedev** [comment]
I'll let @Paul-Bob take this over.

**Comment by UsAndRufus** [comment]
@Paul-Bob Setting `self.model_class` fixed the error. [The docs](https://docs.avohq.io/3.0/associations.html#single-table-inheritance-sti) explains the root cause.

I have the following ActiveRecord:

```ruby
class ClaimScheme < Scheme; end
```

My Avo model is called `Scheme`, but wasn't specifying `model_class`.

I had a relation on my Avo `Scheme`. When trying to attach that relation, the URL generated included `claim_scheme`. Avo couldn't resolve this when clicking on the "attach" button. Setting `self.model_class` meant that the URL generated didn't infer type but rather used `scheme` in it instead.

Hope that helps!
