### ISSUE TITLE
Remove pundit as a mandatory dependency in Avo 3

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avo#2000]
```
rails new some_app
cd some_app
bin/rails app:template LOCATION='https://railsbytes.com/script/V2GskB'
rails server
```

This will prompt you to install pundit when you don't even have the authorization feaure

**Comment by Paul-Bob** [comment]
@adrianthedev reproduced line by line and it doesn't raised any pundit related error on my side

**Comment by Paul-Bob** [comment]
In order to reproduce it i needed to install `avo-pro` and run `rails generate model SomeModel just_a_string` then the error appear 



![Image](https://github.com/avo-hq/avo/assets/69730720/745b19bb-d49a-4326-8db7-977f41c24ec3)

**Comment by Paul-Bob** [comment]
This happen because `config.authorization_client = :pundit` is the default configuration.

We can change it to `config.authorization_client = nil` 

Notice that this is a custom error and we don't have `pundit` as package dependency, this raises when `:pundit` is seted as `authorization_client` and is not installed

**Comment by Paul-Bob** [comment]
I suggest to let it like so and change the message to something like "You have :pundit settend as authorization_client, please add it to your Gemfile or change the authorization_client, more information here: link_to_docs`

**Comment by adrianthedev** [comment]
That's not a good solution for folks that are using the free gem. W need to think about the whole experience.

Can't we consider that the `authorization_client` is `nil` if avo-pro is not present?

**Comment by Paul-Bob** [comment]
> That's not a good solution for folks that are using the free gem. 

Can't reproduce it on `avo`, I needed to install `avo-pro` to experience it.

**Comment by adrianthedev** [comment]
Ok. I'll come back with a better repro

**Comment by xeron** [comment]
Fun fact I had a error about missing `pundit` gem show up in logs with avo 2 (and without `avo-pro`).

**Comment by Paul-Bob** [comment]
> Fun fact I had a error about missing `pundit` gem show up in logs with avo 2 (and without `avo-pro`).

@xeron was that happening on community license?

**Comment by xeron** [comment]
> @xeron was that happening on community license?

Yes. Also for some reason it didn't show up immediately. I had service running for a while and it was working fine, including admin panel, and then suddenly it started returning 500, I checked logs and it was complaining about missing pundit gem in avo engine.

**Comment by xeron** [comment]
Trace of 3 consequential admin panel requests:

```
I, [2023-10-26T17:33:01.175144 #2873595]  INFO -- : [9e1d24ec-57f0-4a5a-865b-4261e7d27ca4] Started GET "/admin/resources/events/oct-21-2023-thunderhill-west-ccw" for IP at 2023-10-26 17:33:01 +0000
I, [2023-10-26T17:33:01.176696 #2873595]  INFO -- : [9e1d24ec-57f0-4a5a-865b-4261e7d27ca4] Processing by Avo::EventsController#show as HTML
I, [2023-10-26T17:33:01.176763 #2873595]  INFO -- : [9e1d24ec-57f0-4a5a-865b-4261e7d27ca4]   Parameters: {"id"=>"oct-21-2023-thunderhill-west-ccw"}
I, [2023-10-26T17:33:01.659335 #2873595]  INFO -- : [9e1d24ec-57f0-4a5a-865b-4261e7d27ca4]   Rendered layout /…/shared/bundle/ruby/3.1.0/gems/avo-2.42.2/app/views/layouts/avo/application.html.erb (Duration: 39.5ms | Allocations: 32023)
I, [2023-10-26T17:33:01.659593 #2873595]  INFO -- : [9e1d24ec-57f0-4a5a-865b-4261e7d27ca4] Completed 200 OK in 483ms (Views: 39.5ms | ActiveRecord: 1.4ms | Allocations: 44757)

I, [2023-10-26T17:33:01.743330 #2879605]  INFO -- : [4a3a7ae8-2656-4912-b4f9-92c74177eee1] Started GET "/admin/resources/events/oct-21-2023-thunderhill-west-ccw/results?turbo_frame=has_many_field_show_results" for IP at 2023-10-26 17:33:01 +0000
I, [2023-10-26T17:33:01.746171 #2879605]  INFO -- : [4a3a7ae8-2656-4912-b4f9-92c74177eee1] Processing by Avo::AssociationsController#index as HTML
I, [2023-10-26T17:33:01.746251 #2879605]  INFO -- : [4a3a7ae8-2656-4912-b4f9-92c74177eee1]   Parameters: {"turbo_frame"=>"has_many_field_show_results", "resource_name"=>"events", "id"=>"oct-21-2023-thunderhill-west-ccw", "related_name"=>"results"}
I, [2023-10-26T17:33:01.783544 #2873595]  INFO -- : [02a80b07-e3c2-4e4f-8a66-3729cc7b2a11] Started GET "/avo-assets/fonts/inter-v7-latin-700.woff2" for IP at 2023-10-26 17:33:01 +0000
I, [2023-10-26T17:33:01.785805 #2873595]  INFO -- sentry: [Transport] Sending envelope with items [transaction] 054e6def7e5f45b4a289769e1c8d7032 to Sentry
E, [2023-10-26T17:33:01.880036 #2879605] ERROR -- : [4a3a7ae8-2656-4912-b4f9-92c74177eee1]   Couldn't find template for digesting: /avo/index/resource_table_component
I, [2023-10-26T17:33:01.893607 #2879605]  INFO -- : [4a3a7ae8-2656-4912-b4f9-92c74177eee1]   Rendered layout /…/shared/bundle/ruby/3.1.0/gems/turbo-rails-1.5.0/app/views/layouts/turbo_rails/frame.html.erb (Duration: 28.2ms | Allocations: 23699)
I, [2023-10-26T17:33:01.893977 #2879605]  INFO -- : [4a3a7ae8-2656-4912-b4f9-92c74177eee1] Completed 200 OK in 148ms (Views: 29.6ms | ActiveRecord: 21.6ms | Allocations: 79008)

I, [2023-10-26T23:41:57.590186 #2908254]  INFO -- : [b90b2586-e87b-415f-96e4-c727752e1158] Started GET "/admin/resources/events/oct-21-2023-thunderhill-west-ccw" for IP at 2023-10-26 23:41:57 +0000
I, [2023-10-26T23:41:57.592014 #2908254]  INFO -- : [b90b2586-e87b-415f-96e4-c727752e1158] Processing by Avo::EventsController#show as HTML
I, [2023-10-26T23:41:57.592071 #2908254]  INFO -- : [b90b2586-e87b-415f-96e4-c727752e1158]   Parameters: {"id"=>"oct-21-2023-thunderhill-west-ccw"}
I, [2023-10-26T23:41:58.028137 #2908254]  INFO -- : [b90b2586-e87b-415f-96e4-c727752e1158] Completed 500 Internal Server Error in 436ms (ActiveRecord: 0.0ms | Allocations: 3059)
E, [2023-10-26T23:41:58.029869 #2908254] ERROR -- : [b90b2586-e87b-415f-96e4-c727752e1158]
[b90b2586-e87b-415f-96e4-c727752e1158] Avo::MissingGemError (Please add `gem 'pundit'` to your Gemfile.):
[b90b2586-e87b-415f-96e4-c727752e1158]
[b90b2586-e87b-415f-96e4-c727752e1158] avo (2.42.2) lib/avo/services/authorization_service.rb:98:in `pundit_client'
[b90b2586-e87b-415f-96e4-c727752e1158] avo (2.42.2) lib/avo/services/authorization_service.rb:18:in `client'
[b90b2586-e87b-415f-96e4-c727752e1158] avo (2.42.2) lib/avo/services/authorization_service.rb:111:in `initialize'
[b90b2586-e87b-415f-96e4-c727752e1158] avo (2.42.2) lib/avo/base_resource.rb:344:in `new'
[b90b2586-e87b-415f-96e4-c727752e1158] avo (2.42.2) lib/avo/base_resource.rb:344:in `authorization'
[b90b2586-e87b-415f-96e4-c727752e1158] avo (2.42.2) app/controllers/avo/application_controller.rb:283:in `set_authorization'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:403:in `block in make_lambda'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:203:in `block in halting'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:598:in `block in invoke_before'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:598:in `each'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:598:in `invoke_before'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:119:in `block in run_callbacks'
[b90b2586-e87b-415f-96e4-c727752e1158] i18n (1.14.1) lib/i18n.rb:322:in `with_locale'
[b90b2586-e87b-415f-96e4-c727752e1158] avo (2.42.2) app/controllers/avo/application_controller.rb:336:in `set_avo_locale'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
[b90b2586-e87b-415f-96e4-c727752e1158] actiontext (7.1.1) lib/action_text/rendering.rb:23:in `with_renderer'
[b90b2586-e87b-415f-96e4-c727752e1158] actiontext (7.1.1) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:130:in `instance_exec'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-rails (5.12.0) lib/sentry/rails/controller_transaction.rb:17:in `block in sentry_around_action'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-ruby (5.12.0) lib/sentry/hub.rb:109:in `block in with_child_span'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-ruby (5.12.0) lib/sentry/span.rb:206:in `with_child_span'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-ruby (5.12.0) lib/sentry/hub.rb:107:in `with_child_span'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-ruby (5.12.0) lib/sentry-ruby.rb:476:in `with_child_span'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-rails (5.12.0) lib/sentry/rails/controller_transaction.rb:14:in `sentry_around_action'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:141:in `run_callbacks'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/abstract_controller/callbacks.rb:258:in `process_action'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_controller/metal/rescue.rb:25:in `process_action'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/notifications.rb:206:in `block in instrument'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-rails (5.12.0) lib/sentry/rails/tracing.rb:54:in `instrument'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/notifications.rb:206:in `instrument'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_controller/metal/instrumentation.rb:73:in `process_action'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
[b90b2586-e87b-415f-96e4-c727752e1158] activerecord (7.1.1) lib/active_record/railties/controller_runtime.rb:32:in `process_action'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/abstract_controller/base.rb:160:in `process'
[b90b2586-e87b-415f-96e4-c727752e1158] actionview (7.1.1) lib/action_view/rendering.rb:40:in `process'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_controller/metal.rb:227:in `dispatch'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_controller/metal.rb:309:in `dispatch'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/journey/router.rb:51:in `block in serve'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/journey/router.rb:124:in `each'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/journey/router.rb:124:in `find_routes'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/routing/route_set.rb:882:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] railties (7.1.1) lib/rails/engine.rb:529:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] railties (7.1.1) lib/rails/railtie.rb:226:in `public_send'
[b90b2586-e87b-415f-96e4-c727752e1158] railties (7.1.1) lib/rails/railtie.rb:226:in `method_missing'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/routing/mapper.rb:22:in `block in <class:Constraints>'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/journey/router.rb:51:in `block in serve'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/journey/router.rb:124:in `each'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/journey/router.rb:124:in `find_routes'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/routing/route_set.rb:882:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] rack (2.2.8) lib/rack/static.rb:161:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] rack (2.2.8) lib/rack/tempfile_reaper.rb:15:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] rack (2.2.8) lib/rack/etag.rb:27:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] rack (2.2.8) lib/rack/conditional_get.rb:27:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] rack (2.2.8) lib/rack/head.rb:12:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] rack (2.2.8) lib/rack/session/abstract/id.rb:266:in `context'
[b90b2586-e87b-415f-96e4-c727752e1158] rack (2.2.8) lib/rack/session/abstract/id.rb:260:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-rails (5.12.0) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-ruby (5.12.0) lib/sentry/rack/capture_exceptions.rb:28:in `block (2 levels) in call'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-ruby (5.12.0) lib/sentry/hub.rb:251:in `with_session_tracking'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-ruby (5.12.0) lib/sentry-ruby.rb:387:in `with_session_tracking'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-ruby (5.12.0) lib/sentry/rack/capture_exceptions.rb:19:in `block in call'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-ruby (5.12.0) lib/sentry/hub.rb:59:in `with_scope'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-ruby (5.12.0) lib/sentry-ruby.rb:367:in `with_scope'
[b90b2586-e87b-415f-96e4-c727752e1158] sentry-ruby (5.12.0) lib/sentry/rack/capture_exceptions.rb:18:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] railties (7.1.1) lib/rails/rack/logger.rb:37:in `call_app'
[b90b2586-e87b-415f-96e4-c727752e1158] railties (7.1.1) lib/rails/rack/logger.rb:24:in `block in call'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/tagged_logging.rb:135:in `block in tagged'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/tagged_logging.rb:39:in `tagged'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/tagged_logging.rb:135:in `tagged'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/broadcast_logger.rb:232:in `method_missing'
[b90b2586-e87b-415f-96e4-c727752e1158] railties (7.1.1) lib/rails/rack/logger.rb:24:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/middleware/request_id.rb:28:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] rack (2.2.8) lib/rack/method_override.rb:24:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] rack (2.2.8) lib/rack/runtime.rb:22:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] activesupport (7.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/middleware/ssl.rb:79:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] actionpack (7.1.1) lib/action_dispatch/middleware/assume_ssl.rb:21:in `call'
[b90b2586-e87b-415f-96e4-c727752e1158] railties (7.1.1) lib/rails/engine.rb:529:in `call'
```

I checked logs between `2023-10-26T17:33:01.893977` and `2023-10-26T23:41:57.590186` but didn't find anything related to `avo`.

**Comment by Paul-Bob** [comment]
Thank you for the details @xeron ! I'll dig more into it

**Comment by Paul-Bob** [comment]
On avo3 `Avo::MissingGemError` error is raised from `avo-pro` https://github.com/avo-hq/avo-pro/blob/main/lib/avo/pro/authorization/authorization_service.rb#L99

I let my server run for some time and played around with it without any error.

I'll close the issue as completed since can't reproduce it (tried to reproduce multiple times), please reopen it and include some prints / back-trace if catch this error again.

**Comment by adrianthedev** [comment]
I cna't reproduce it either. Maybe it was fixed. Thanks for looking into it!
