### ISSUE TITLE
Stimulus controllers won't load

### ISSUE THREAD

**Issue by nhorton** [avo-hq/avo#2011]
This is a follow-on of sorts to issue #2003 . Once that was fixed, I now get the file to load but all the stimulus controllers in the importmap generate browser errors like the following:
```
stimulus-loading-1fc53fe7a488db9281d2ff88509e8f45d6119ee4.js:71 Failed to autoload controller: item-select-all TypeError: Failed to resolve module specifier 'controllers/item_select_all_controller'
    at loadController (stimulus-loading-1fc53fe7a488db9281d2ff88509e8f45d6119ee4.js:69:12)
    at stimulus-loading-1fc53fe7a488db9281d2ff88509e8f45d6119ee4.js:38:65
    at Array.forEach (<anonymous>)
    at lazyLoadExistingControllers (stimulus-loading-1fc53fe7a488db9281d2ff88509e8f45d6119ee4.js:38:39)
    at MutationObserver.observe.attributeFilter (stimulus-loading-1fc53fe7a488db9281d2ff88509e8f45d6119ee4.js:52:11)
```
These all load fine in the main part of the app with the standard loading from the normal application.js. The code in my customized JS file for Avo is:
```
import "@hotwired/turbo-rails"
import "controllers"
```
Any ideas?

**Comment by xeron** [comment]
Not sure if this is going to help you but there's a bug in the docs which I noticed while adding stimulus controller to avo:

https://github.com/avo-hq/avodocs/issues/107

**Comment by adrianthedev** [comment]
Is this still an issue @nhorton?

**Comment by adrianthedev** [comment]
Closing for now. Please feel free to reopen if this is still an issue.
