### ISSUE TITLE
Avo::AlertComponent raises 500 error

### ISSUE THREAD

**Issue by johannesengl** [avo-hq/avo#2023]
### Describe the bug

Avo::AlertComponent raises 500 error due to being initiated with invalid parameters. 

### Steps to Reproduce

I have the following resource: 
```
# frozen_string_literal: true

class InventoryResource < Avo::BaseResource
  self.title = :id
  self.includes = %i[provider store team team_lead_user region]
  self.search_query = lambda {
    scope.ransack(id_eq: params[:q], instructions_cont: params[:q], m: "or").result(distinct: false)
  }

  field :id, as: :id, link_to_resource: true
  field :scheduled_for, as: :date_time
  field :started_at, as: :date_time
  field :ended_at, as: :date_time
  field :instructions, as: :text
  field :provider, as: :belongs_to
  field :store, as: :belongs_to
  field :team, as: :belongs_to
  field :team_lead_user, as: :belongs_to
  field :password, as: :text, show_on: :show
  field :users, as: :has_and_belongs_to_many
end

```

I attach a user to the inventory via the has and belongs to many association. The SQL query inserting the row in the inventories_users table gets committed successfully and I get redirected back to the inventory show page. See development logs:

```
Started POST "/admin/resources/inventories/018baaac-ed9f-77a0-9dbd-427f5dc4b0cb/users" for ::1 at 2023-11-10 10:12:08 +0000
Processing by Avo::AssociationsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "fields"=>{"related_id"=>"018ba9de-56c2-78ab-945d-b6a6c50a22b3"}, "button"=>"", "resource_name"=>"inventories", "id"=>"018baaac-ed9f-77a0-9dbd-427f5dc4b0cb", "related_name"=>"users"}
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", "018b8fbe-be7c-7dbc-b305-81e8df7e43f7"], ["LIMIT", 1]]
  Inventory Load (1.5ms)  SELECT "inventories".* FROM "inventories" WHERE "inventories"."id" = $1 LIMIT $2  [["id", "018baaac-ed9f-77a0-9dbd-427f5dc4b0cb"], ["LIMIT", 1]]
  User Load (1.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", "018ba9de-56c2-78ab-945d-b6a6c50a22b3"], ["LIMIT", 1]]
  TRANSACTION (7.5ms)  BEGIN
  Inventory::HABTM_Users Create (3.7ms)  INSERT INTO "inventories_users" ("inventory_id", "user_id") VALUES ($1, $2)  [["inventory_id", "018baaac-ed9f-77a0-9dbd-427f5dc4b0cb"], ["user_id", "018ba9de-56c2-78ab-945d-b6a6c50a22b3"]]
  TRANSACTION (1.4ms)  COMMIT
  TRANSACTION (1.3ms)  BEGIN
  Provider Load (0.3ms)  SELECT "providers".* FROM "providers" WHERE "providers"."id" = $1 LIMIT $2  [["id", "018ba9de-5719-7e0b-86a5-6f0d58357fbe"], ["LIMIT", 1]]
  Store Load (0.3ms)  SELECT "stores".* FROM "stores" WHERE "stores"."id" = $1 LIMIT $2  [["id", "018ba9de-7a0d-7f91-a912-5e51cad12cd8"], ["LIMIT", 1]]
  TRANSACTION (1.1ms)  COMMIT
Redirected to http://localhost:3000/admin/resources/inventories/018baaac-ed9f-77a0-9dbd-427f5dc4b0cb
Completed 302 Found in 77ms (ActiveRecord: 18.8ms | Allocations: 21570)
```

Now the Avo::AlertComponent gets initiated with invalid parameters for type and message. type is passed as false and message as  :allow_other_host:

```
Avo::AlertComponent.new(false, :allow_other_host).classes
```

This raises the following error: 

```
ActionView::Template::Error (no implicit conversion of nil into String):
    47:     <%= turbo_frame_tag 'actions_show' %>
    48:     <%= turbo_frame_tag 'attach_modal' %>
    49:     <%= turbo_frame_tag 'alerts', class: "fixed inset-0 bottom-0 flex flex-col space-y-4 items-end justify-right px-4 py-6 sm:p-6 justify-end z-[100] pointer-events-none" do %>
    50:       <%= render Avo::FlashAlertsComponent.new flashes: flash %>
    51:       <% # In case we have other general error messages %>
    52:       <% if @errors.present? %>
    53:         <% @errors.each do |message| %>
  
avo (2.44.0) app/components/avo/alert_component.rb:28:in `+'
avo (2.44.0) app/components/avo/alert_component.rb:28:in `classes'
avo (2.44.0) app/components/avo/alert_component.html.erb:4:in `call'
view_component (3.7.0) lib/view_component/compiler.rb:120:in `render_template_for'
view_component (3.7.0) lib/view_component/base.rb:106:in `render_in'
actionview (7.0.7.2) lib/action_view/helpers/rendering_helper.rb:42:in `render'
view_component (3.7.0) lib/view_component/base.rb:189:in `render'
avo (2.44.0) app/components/avo/flash_alerts_component.html.erb:2:in `block in call'
actionpack (7.0.7.2) lib/action_dispatch/middleware/flash.rb:199:in `each'
actionpack (7.0.7.2) lib/action_dispatch/middleware/flash.rb:199:in `each'
avo (2.44.0) app/components/avo/flash_alerts_component.html.erb:1:in `call'
view_component (3.7.0) lib/view_component/compiler.rb:120:in `render_template_for'
view_component (3.7.0) lib/view_component/base.rb:106:in `render_in'
actionview (7.0.7.2) lib/action_view/helpers/rendering_helper.rb:42:in `render'
avo (2.44.0) app/views/layouts/avo/application.html.erb:50
actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:45:in `capture'
actionview (7.0.7.2) lib/action_view/helpers/tag_helper.rb:71:in `tag_string'
actionview (7.0.7.2) lib/action_view/helpers/tag_helper.rb:189:in `method_missing'
turbo-rails (1.4.0) app/helpers/turbo/frames_helper.rb:42:in `turbo_frame_tag'
avo (2.44.0) app/views/layouts/avo/application.html.erb:49
actionview (7.0.7.2) lib/action_view/base.rb:244:in `public_send'
actionview (7.0.7.2) lib/action_view/base.rb:244:in `_run'
actionview (7.0.7.2) lib/action_view/template.rb:157:in `block in render'
```

### Expected behavior & Actual behavior

The view component should handle gracefully to be called with invalid parameters. Furthermore, there is probably a bug which leads to the behaviour that this component is called with invalid data in the first place. 

### System configuration
**Avo version**:  avo (2.44.0)

**Rails version**: 7.0.7

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by johannesengl** [comment]
@Paul-Bob Any update on this?

**Comment by adrianthedev** [comment]
Hey @johannesengl we have a public holiday for the next few days and we are off. I'll add this to the top of the pile for @Paul-Bob to look at next week.
Not sure how we missed triaging it.

**Comment by johannesengl** [comment]
> Hey @johannesengl we have a public holiday for the next few days and we are off. I'll add this to the top of the pile for @Paul-Bob to look at next week.
> Not sure how we missed triaging it.

Amazing. Thanks a lot!

**Comment by johannesengl** [comment]
@Paul-Bob Thanks for looking into this. I currently dont have the time to setup a reproduction repository. We fixed the issue on our side.

**Comment by Paul-Bob** [comment]
That's fine @johannesengl glad that you fixed it, any clue why it was getting initialized with `(false, :allow_other_host)`?

**Comment by adrianthedev** [comment]
Yes @johannesengl, we'd love to find out what was the fix.

**Comment by adrianthedev** [comment]
Hey @jasdeepsingh.
Thanks for reporting this.

This initial report was made for Avo 2.x and a lot has changed since then.

In order to properly debug the error, please open a new issue with the required information on there and the stack trace.
