### ISSUE TITLE
ActionView::Template::Error (unknown keyword: :dynamic_filters_component_id)

### ISSUE THREAD

**Issue by AhmedAliIbrahim** [avo-hq/avo#2040]
We've recently upgraded to avo3 advanced license and we're getting ActionView::Template::Error (unknown keyword: :dynamic_filters_component_id) when we try to use dynamic filters

### Steps to Reproduce
1. upgrade to avo 3 beta
2. use dynamic filters by adding filterable: true to existing field
3. run the app

### Expected behavior & Actual behavior
it should work  fine

### System configuration
**Avo version**: avo 3 beta

**Rails version**: 7.0.7

**Ruby version**: 3.2.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Can you please provide more of the stacktrace? In what file is the error raised?
Also, what kind of field you marked as filterable.

**Comment by AhmedAliIbrahim** [comment]
date_time field


`[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] ActionView::Template::Error (unknown keyword: :dynamic_filters_component_id):
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7]     1: <%= render Avo::TurboFrameWrapperComponent.new(params[:turbo_frame]) do %>
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7]     2:   <%= render @component.new(
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7]     3:       resource: @resource,
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7]     4:       resources: @resources,
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7]     5:       records: @records,
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7]   
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] avo-dynamic_filters (0.5.19) app/components/avo/dynamic_filters/filters_component.rb:10:in `initialize'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] avo (3.0.1.beta24) app/components/avo/views/resource_index_component.html.erb:38:in `new'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] avo (3.0.1.beta24) app/components/avo/views/resource_index_component.html.erb:38:in `block (3 levels) in call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:45:in `capture'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] view_component (3.7.0) lib/view_component/slot.rb:67:in `to_s'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/buffers.rb:29:in `<<'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] avo (3.0.1.beta24) app/components/avo/panel_component.html.erb:31:in `block in call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:45:in `capture'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/tag_helper.rb:371:in `content_tag'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] avo (3.0.1.beta24) app/components/avo/panel_component.html.erb:1:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] view_component (3.7.0) lib/view_component/compiler.rb:120:in `render_template_for'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] view_component (3.7.0) lib/view_component/base.rb:106:in `render_in'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/rendering_helper.rb:42:in `render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] view_component (3.7.0) lib/view_component/base.rb:189:in `render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] avo (3.0.1.beta24) app/components/avo/views/resource_index_component.html.erb:9:in `block in call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:45:in `capture'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/tag_helper.rb:371:in `content_tag'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] avo (3.0.1.beta24) app/components/avo/views/resource_index_component.html.erb:1:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] view_component (3.7.0) lib/view_component/compiler.rb:120:in `render_template_for'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] view_component (3.7.0) lib/view_component/base.rb:106:in `render_in'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/rendering_helper.rb:42:in `render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] avo (3.0.1.beta24) app/views/avo/base/index.html.erb:2
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/capture_helper.rb:45:in `capture'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] view_component (3.7.0) lib/view_component/base.rb:274:in `content'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] avo (3.0.1.beta24) app/components/avo/turbo_frame_wrapper_component.html.erb:9:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] view_component (3.7.0) lib/view_component/compiler.rb:120:in `render_template_for'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] view_component (3.7.0) lib/view_component/base.rb:106:in `render_in'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/helpers/rendering_helper.rb:42:in `render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] avo (3.0.1.beta24) app/views/avo/base/index.html.erb:1
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/base.rb:244:in `public_send'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/base.rb:244:in `_run'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/template.rb:157:in `block in render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/notifications.rb:208:in `instrument'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/template.rb:361:in `instrument_render_template'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/template.rb:155:in `render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/notifications.rb:206:in `block in instrument'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/notifications.rb:206:in `instrument'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/renderer/template_renderer.rb:75:in `block in render_with_layout'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/notifications.rb:206:in `block in instrument'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/notifications.rb:206:in `instrument'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/renderer/template_renderer.rb:11:in `render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/rendering.rb:117:in `block in _render_template'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/base.rb:270:in `in_rendering_context'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/rendering.rb:116:in `_render_template'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/streaming.rb:216:in `_render_template'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/rendering.rb:103:in `render_to_body'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/rendering.rb:158:in `render_to_body'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/abstract_controller/rendering.rb:27:in `render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/rendering.rb:139:in `render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/instrumentation.rb:22:in `block (2 levels) in render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] /usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/core_ext/benchmark.rb:14:in `ms'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/instrumentation.rb:22:in `block in render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/instrumentation.rb:91:in `cleanup_view_runtime'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activerecord (7.0.7.2) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/instrumentation.rb:21:in `render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] meta-tags (2.19.0) lib/meta_tags/controller_helper.rb:22:in `render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/basic_implicit_render.rb:7:in `send_action'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/abstract_controller/base.rb:215:in `process_action'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/rendering.rb:165:in `process_action'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] i18n (1.14.1) lib/i18n.rb:322:in `with_locale'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] avo (3.0.1.beta24) app/controllers/avo/application_controller.rb:281:in `set_avo_locale'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actiontext (7.0.7.2) lib/action_text/rendering.rb:20:in `with_renderer'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actiontext (7.0.7.2) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/callbacks.rb:127:in `instance_exec'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/callbacks.rb:138:in `run_callbacks'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/abstract_controller/callbacks.rb:233:in `process_action'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/rescue.rb:23:in `process_action'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/notifications.rb:206:in `block in instrument'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/notifications.rb:206:in `instrument'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activerecord (7.0.7.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/abstract_controller/base.rb:151:in `process'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionview (7.0.7.2) lib/action_view/rendering.rb:39:in `process'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal.rb:188:in `dispatch'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_controller/metal.rb:251:in `dispatch'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/journey/router.rb:32:in `each'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/journey/router.rb:32:in `serve'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/routing/route_set.rb:852:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] railties (7.0.7.2) lib/rails/engine.rb:530:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] railties (7.0.7.2) lib/rails/railtie.rb:226:in `public_send'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] railties (7.0.7.2) lib/rails/railtie.rb:226:in `method_missing'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/journey/router.rb:32:in `each'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/journey/router.rb:32:in `serve'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/routing/route_set.rb:852:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/static.rb:161:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/static.rb:161:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/static.rb:161:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/static.rb:161:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/tempfile_reaper.rb:15:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/etag.rb:27:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/conditional_get.rb:27:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/head.rb:12:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/session/abstract/id.rb:266:in `context'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/session/abstract/id.rb:260:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/middleware/cookies.rb:704:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/callbacks.rb:99:in `run_callbacks'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] railties (7.0.7.2) lib/rails/rack/logger.rb:40:in `call_app'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] railties (7.0.7.2) lib/rails/rack/logger.rb:25:in `block in call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/tagged_logging.rb:37:in `tagged'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] activesupport (7.0.7.2) lib/active_support/tagged_logging.rb:99:in `tagged'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] railties (7.0.7.2) lib/rails/rack/logger.rb:25:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/method_override.rb:24:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/runtime.rb:22:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/middleware/static.rb:23:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] actionpack (7.0.7.2) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] railties (7.0.7.2) lib/rails/engine.rb:530:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] puma (6.4.0) lib/puma/configuration.rb:272:in `call'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] puma (6.4.0) lib/puma/request.rb:100:in `block in handle_request'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] puma (6.4.0) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] puma (6.4.0) lib/puma/request.rb:99:in `handle_request'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] puma (6.4.0) lib/puma/server.rb:443:in `process_client'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] puma (6.4.0) lib/puma/server.rb:241:in `block in run'
[893a44f5-ab00-4fa3-a1b0-be7a357fb0a7] puma (6.4.0) lib/puma/thread_pool.rb:155:in `block in spawn_thread'`

**Comment by Paul-Bob** [comment]
@AhmedAliIbrahim can you provide the versions for each avo related gem from your `Gemfile.lock` please?

**Comment by adrianthedev** [comment]
@AhmedAliIbrahim please add `gem 'avo', '>= 3.1.0"` to your gemfile and then run `bundle update avo avo-advanced`

**Comment by adrianthedev** [comment]
Closing for now. Please re-open if this still persists.
