### ISSUE TITLE
The TextFilter function cannot search for some characters

### ISSUE THREAD

**Issue by yuki-yogi** [avo-hq/avo#2061]
### Describe the bug
- The TextFilter function cannot search for some characters.
  - Search may not be possible in languages other than English. The impact is likely to be especially large in Asia in general.

### Steps to Reproduce
1. Access at https://avodemo.com/avo/resources/users
2. Press the Filter button
3. Enter the word `(` or `音楽` in the User names filter input form (音楽 means music in Japanese).
4. Click the Filter by user names button
5. javascript error and cannot search
```
stimulus.js:2017 Error invoking action "keypress->text-filter#tryToSubmit"
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at n.b64DecodeUnicode (filter_controller.js:38:12)
    at n.changeFilter (filter_controller.js:50:33)
    at n.tryToSubmit (text_filter_controller.js:12:19)
    at tse.invokeWithEvent (stimulus.js:362:25)
    at tse.handleEvent (stimulus.js:329:18)
    at Xae.handleEvent (stimulus.js:31:25)

{identifier: 'text-filter', controller: n, element: div, index: 0, event: KeyboardEvent}controller: n {context: fse}element: divevent: KeyboardEvent {isTrusted: true, immediatePropagationStopped: false, params: {…}, key: 'Enter', stopImmediatePropagation: ƒ, …}identifier: "text-filter"index: 0[[Prototype]]: Object
handleError @ stimulus.js:2017
handleError @ stimulus.js:1423
invokeWithEvent @ stimulus.js:368
handleEvent @ stimulus.js:329
handleEvent @ stimulus.js:31
```

### Expected behavior & Actual behavior
To be able to search by text entered in text-filte.

### System configuration
**Avo version**:
3.0.6

**Rails version**:
7.1.2

**Ruby version**:
3.2.2

**License type**:
 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
https://github.com/avo-hq/avo/assets/14293538/068e30b9-cb6a-49bd-9689-4df28f0211e4

https://github.com/avo-hq/avo/assets/14293538/92dc9def-88d4-4d2f-97be-af12e0d42189

#### Impact
We plan to temporarily disable the text filter for all resources to work around this issue.

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency
 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by yuki-yogi** [comment]
As shown below, an error occurred because filter_params contained a space, so when I replaced the space with + and added processing, I was able to search once.
However, when I tried searching again, a javascript error occurred.

```
module Avo
  module Filters
    class BaseFilter
      ...
      class << self
        def decode_filters(filter_params)
          pp "=======filter_params::#{filter_params}"
          # filter_params may contain spaces, replace with +.
          filter_params = filter_params.gsub(/[\u3000 ]/, '+')
          pp "=======filter_params::#{filter_params}"
          JSON.parse(Base64.decode64(filter_params))
        rescue
          {}
        end
```

> "=======filter_params::eyJBdm86OkZpbHRlcnM6OlRpdGxlRmlsdGVyIjoi6Z z5qW9In0="
> "=======filter_params::eyJBdm86OkZpbHRlcnM6OlRpdGxlRmlsdGVyIjoi6Z+z5qW9In0="

```
{identifier: 'text-filter', controller: n, element: div, index: 0, event: PointerEvent}
handleError @ stimulus.js:2017
handleError @ stimulus.js:1423
invokeWithEvent @ stimulus.js:368
handleEvent @ stimulus.js:329
handleEvent @ stimulus.js:31
stimulus.js:2017 Error invoking action "click->text-filter#changeFilter"

DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at n.b64DecodeUnicode (http://localhost:3000/avo-assets/avo.base.js:538:77532)
    at n.changeFilter (http://localhost:3000/avo-assets/avo.base.js:538:77752)
    at tse.invokeWithEvent (http://localhost:3000/avo-assets/avo.base.js:534:205536)
    at tse.handleEvent (http://localhost:3000/avo-assets/avo.base.js:534:204927)
    at Xae.handleEvent (http://localhost:3000/avo-assets/avo.base.js:534:201021)

{identifier: 'text-filter', controller: n, element: div, index: 0, event: PointerEvent}
handleError @ stimulus.js:2017
handleError @ stimulus.js:1423
invokeWithEvent @ stimulus.js:368
handleEvent @ stimulus.js:329
handleEvent @ stimulus.js:
```


https://github.com/avo-hq/avo/assets/14293538/d9c2f770-5f0f-4332-be74-a5b8a744d00b
