### ISSUE TITLE
Uninitialized constant Avo::Plugin

### ISSUE THREAD

**Issue by yashka713** [avo-hq/avo#2080]
### Describe the bug

I have avo pro licence and when I am re-creating `Gemfile.lock` after upgrading to `avo-pro` Gem and V3 avo version

I got:

```shell
gems/avo-pro-0.1.55/lib/avo/pro/plugin.rb:3:in `<module:Pro>': uninitialized constant Avo::Plugin (NameError)

    class Plugin < Avo::Plugin
                      ^^^^^^^^
        from /Users/Yaroslav/.rvm/gems/ruby-3.2.2@lite/gems/avo-pro-0.1.55/lib/avo/pro/plugin.rb:2:in `<module:Avo>'
        from /Users/Yaroslav/.rvm/gems/ruby-3.2.2@lite/gems/avo-pro-0.1.55/lib/avo/pro/plugin.rb:1:in `<main>'
```

my `Gemfile`

```ruby
gem "avo-pro", source: "https://packager.dev/avo-hq/"
```

My newly generated `Gemfile.lock` said that the avo version is `2.45.0`, but this version do not have Plugin constant yet.

Could you update dependencies for `avo-pro (0.1.55)` to fix it?

<img width="272" alt="Screenshot 2023-12-04 at 17 33 41" src="https://github.com/avo-hq/avo/assets/15985355/5f6fddaa-838b-4f59-a471-e55ae7b02425">

### Steps to Reproduce
0. Clear `gemset`
1. Left only `gem "avo-pro", source: "https://packager.dev/avo-hq/"` in Gemfile
2. Run `bundle install`
3. Run `rails server`

### Expected behavior & Actual behavior

It is available ti use AVO V3 for pro version

### System configuration
**Avo version**: 2.45.0

**Rails version**:7.1.0

**Ruby version**:3.2.2

**License type**:

 - [ ] Community
 - [ x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x ] No

#### Impact

 - [ x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by yashka713** [comment]
https://docs.avohq.io/3.0/gem-server-authentication.html#on-the-server-and-ci-systems

```shell
export BUNDLE_PACKAGER__DEV=xxx
# or
BUNDLE_PACKAGER__DEV=xxx bundle install
```

**Comment by yashka713** [comment]
@adrianthedev JFYI 

Avo `3.0.7` is incompatible with Heroku.

Deploying fails when running `rake assets:precompile`. Avo tried to create a log file inside the Heroku file system and failed because it is impossible.

Avo `3.1.0` with a new custom logger fixes it.

In my case I just define it like:

```ruby
 ## == Logger ==
  config.logger = -> {
    file_logger = Logger.new(STDOUT)
    file_logger.datetime_format = "%Y-%m-%d %H:%M:%S"
    file_logger.formatter = proc do |severity, time, progname, msg|
      "[Avo] #{time}: #{msg}\n".tap do |i|
        puts i
      end
    end
    file_logger
  }
```

**Comment by adrianthedev** [comment]
Thanks for getting back to us this @yashka713.

Could you send over a stack trace? I deployed our demo app on heroku with Avo 3.0.7 and 3.1.0  and couldn't replicate the crash.

**Comment by yashka713** [comment]
Sure

```shell
Running: rake assets:precompile

rake aborted!
       Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/build_0ae47dc1/log/avo.log (Errno::ENOENT)
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/logger.rb:81:in `initialize'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/avo-3.0.7/lib/avo.rb:131:in `new'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/avo-3.0.7/lib/avo.rb:131:in `boot_logger'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/avo-3.0.7/lib/avo.rb:52:in `boot'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/avo-3.0.7/lib/avo/engine.rb:45:in `block in <class:Engine>'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:445:in `instance_exec'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:445:in `block in make_lambda'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:687:in `block (2 levels) in default_terminator'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:686:in `catch'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:686:in `block in default_terminator'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:200:in `block in halting'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `block in invoke_before'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `each'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `invoke_before'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:106:in `run_callbacks'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/reloader.rb:88:in `prepare!'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application/finisher.rb:68:in `block in <module:Finisher>'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `instance_exec'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `run'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:61:in `block in run_initializers'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:60:in `run_initializers'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:372:in `initialize!'
       /tmp/build_0ae47dc1/config/environment.rb:5:in `<main>'
       <internal:/tmp/build_0ae47dc1/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
       <internal:/tmp/build_0ae47dc1/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:348:in `require_environment!'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:506:in `block in run_tasks_blocks'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
       
       Caused by:
       Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/build_0ae47dc1/log/avo.log (Errno::ENOENT)
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/logger.rb:81:in `initialize'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/avo-3.0.7/lib/avo.rb:131:in `new'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/avo-3.0.7/lib/avo.rb:131:in `boot_logger'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/avo-3.0.7/lib/avo.rb:52:in `boot'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/avo-3.0.7/lib/avo/engine.rb:45:in `block in <class:Engine>'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:445:in `instance_exec'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:445:in `block in make_lambda'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:687:in `block (2 levels) in default_terminator'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:686:in `catch'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:686:in `block in default_terminator'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:200:in `block in halting'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `block in invoke_before'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `each'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `invoke_before'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:106:in `run_callbacks'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/reloader.rb:88:in `prepare!'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application/finisher.rb:68:in `block in <module:Finisher>'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `instance_exec'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `run'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:61:in `block in run_initializers'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:60:in `run_initializers'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:372:in `initialize!'
       /tmp/build_0ae47dc1/config/environment.rb:5:in `<main>'
       <internal:/tmp/build_0ae47dc1/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
       <internal:/tmp/build_0ae47dc1/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:348:in `require_environment!'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:506:in `block in run_tasks_blocks'
       /tmp/build_0ae47dc1/vendor/bundle/ruby/3.2.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)

 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by veelenga** [comment]
Faced the same issue. This happens when `log` folder does not exist (i.e. rails logger logs to STDOUT instead of a file).
