### ISSUE TITLE
Cannot read properties of null (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#2414]
### Approach

- [ ] add a check to the `isInViewport` method to see if the elements are present

### Describe the bug
The console shows this error on some crm_item_document#new form:

```
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at D1t (avo.base.js:57:24)
    at O1t (avo.base.js:73:8)
    at HTMLDocument.<anonymous> (avo.base.js:88:5)
    at Yc (turbo.es2017-esm.js:344:34)
    at O4.notifyApplicationAfterPageLoad (turbo.es2017-esm.js:3158:16)
    at O4.visitCompleted (turbo.es2017-esm.js:3062:14)
    at w4.visitCompleted (turbo.es2017-esm.js:2417:23)
    at v4.complete (turbo.es2017-esm.js:1787:31)
    at turbo.es2017-esm.js:1854:26
    at async v4.render (turbo.es2017-esm.js:2037:9)
````

### Models and resource files
The resource itself:
```ruby
class Avo::Resources::CrmItemDocument < Avo::BaseResource
  self.includes = [:ref_doc_type, :item]
  self.title = lambda {
    [record.item.full_name, record.ref_doc_type.name, record.reference].compact_blank.join(' - ')
  }

  def index_fields
    field :ref_doc_type, as: :belongs_to
    field :reference, as: :text
    field :expires_on, as: :date
  end

  def fields
    main_panel do
      field :ref_doc_type, as: :belongs_to, can_create: false, name: 'Document Type', attach_scope: -> { query.in_contact }
      field :file, as: :file
      field :reference, as: :text
      field :expires_on, as: :date
      field :item, as: :belongs_to, can_create: false, polymorphic_as: :item, types: [::Contact, ::Company], searchable: true
    end
  end
end

```

### System configuration
**Avo version**:
3.3.2

**Rails version**:
7.1.3

**Ruby version**:
3.3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
I think it's related to the sidebar.
Have you ejected anything in the sidebar?
When you click on `avo.base.js:57:24`, what piece of code do you see?

**Comment by jetienne** [comment]
Here is the code:
![Screenshot 2024-01-26 at 14 49 21](https://github.com/avo-hq/avo/assets/201689/19470f43-ed34-4ff1-a356-5ab89c0d01a4)

Note: I am not really using sidebar on the project, only in one place, and in a different resource the page the exception raised.

**Comment by adrianthedev** [comment]
Oh, interesting! That's the culprit.
I'll push a fix. I see it's not burning (urgent)!

Curious, are you using your own sidebar or going somehow sidebar-less?

**Comment by jetienne** [comment]
Not urgent at all for me, I just started to implement some Stimulus controllers and wanted to catch client side errors with Rollbar... 

I am sidebar-less for the project for now :)

**Comment by jetienne** [comment]
@adrianthedev This was closed 1 month ago, but still having the issue. Will it be part of the next release? Any rough ETA? Thanks!

**Comment by Paul-Bob** [comment]
@jetienne a fix for this was released with `[v3.4.0](https://github.com/avo-hq/avo/releases/tag/v3.4.0)` 

What version are you using?

**Comment by jetienne** [comment]
I am always using the latest version: avo (3.4.1)

**Comment by adrianthedev** [comment]
@jetienne I think this is fixed by https://github.com/avo-hq/avo/pull/2759.

Please check on latest and we'll re-open it
