### ISSUE TITLE
Avo Status broken in development

### ISSUE THREAD

**Issue by jetienne** [avo-hq/avo#2533]
### Describe the bug

Avo status page is broken in development

### Steps to Reproduce

- Open Avo UI
- Click on App Status (/admin/avo_private/status)
- See error:

```ruby
cannot load such file -- /.../ruby/gems/3.3.0/gems/avo/lib/avo/version

require_relative "lib/avo/dashboards/version"
require_relative "../avo/lib/avo/version"

Gem::Specification.new do |spec|
  spec.name = "avo-dashboards"
  spec.version = Avo::Dashboards::VERSION
```

### System configuration
**Avo version**:
3.4.2

**Rails version**:
7.1.3.2

**Ruby version**:
3.3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Is this still an issue @jetienne?

**Comment by jetienne** [comment]
@adrianthedev Still on issue on my side. You don't reproduce it?

**Comment by adrianthedev** [comment]
Nope. I can see the page fine.

**Comment by ONLYstcm** [comment]
I'm getting the same error after just installing the pro version

**Comment by adrianthedev** [comment]
Can you please send the stacktrace you get in the Rails console (output) here. Ofc you can remove the sensitive information from it.

**Comment by ONLYstcm** [comment]
I just updated the avo avo-pro and avo-dashboard libraries to 3.9.1 and it's working again

**Comment by adrianthedev** [comment]
Yeah. There was a bug with Rails 7.1.

Please check out [this guide](https://docs.avohq.io/3.0/upgrade.html#upgrade-from-3-7-4-to-3-9-1).

**Comment by rctneil** [comment]
This occurs for me.  Happing on 3.15.0 and the same on previous versions.  Running in development on Rails 7.2.2.

Clicking Avo Status results in 

```
"Routing Error
No route matches
Rails.root: /workspaces/neiltongesite"
```

Not sure if the trace will be helpful but for reference it is:

```
[avo (3.15.0) app/controllers/avo/base_application_controller.rb:337:in `raise_404'](http://localhost:3000/avo/avo_private/status#)
[avo (3.15.0) app/controllers/avo/base_application_controller.rb:333:in `authenticate_developer_or_admin!'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:362:in `block in make_lambda'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:179:in `block in call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:180:in `call'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:559:in `block in invoke_before'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:559:in `each'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:559:in `invoke_before'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:119:in `block in run_callbacks'](http://localhost:3000/avo/avo_private/status#)
[i18n (1.14.6) lib/i18n.rb:353:in `with_locale'](http://localhost:3000/avo/avo_private/status#)
[avo (3.15.0) app/controllers/avo/base_application_controller.rb:287:in `set_avo_locale'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:130:in `block in run_callbacks'](http://localhost:3000/avo/avo_private/status#)
[turbo-rails (2.0.11) lib/turbo-rails.rb:24:in `with_request_id'](http://localhost:3000/avo/avo_private/status#)
[turbo-rails (2.0.11) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:130:in `block in run_callbacks'](http://localhost:3000/avo/avo_private/status#)
[actiontext (7.2.2) lib/action_text/rendering.rb:25:in `with_renderer'](http://localhost:3000/avo/avo_private/status#)
[actiontext (7.2.2) lib/action_text/engine.rb:71:in `block (4 levels) in <class:Engine>'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:130:in `instance_exec'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:130:in `block in run_callbacks'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:141:in `run_callbacks'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/abstract_controller/callbacks.rb:260:in `process_action'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_controller/metal/rescue.rb:27:in `process_action'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_controller/metal/instrumentation.rb:77:in `block in process_action'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/notifications.rb:210:in `block in instrument'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/notifications/instrumenter.rb:58:in `instrument'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/notifications.rb:210:in `instrument'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_controller/metal/instrumentation.rb:76:in `process_action'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'](http://localhost:3000/avo/avo_private/status#)
[activerecord (7.2.2) lib/active_record/railties/controller_runtime.rb:39:in `process_action'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/abstract_controller/base.rb:163:in `process'](http://localhost:3000/avo/avo_private/status#)
[actionview (7.2.2) lib/action_view/rendering.rb:40:in `process'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_controller/metal.rb:252:in `dispatch'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_controller/metal.rb:335:in `dispatch'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/routing/route_set.rb:67:in `dispatch'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/routing/route_set.rb:50:in `serve'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/journey/router.rb:53:in `block in serve'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/journey/router.rb:133:in `block in find_routes'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/journey/router.rb:126:in `each'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/journey/router.rb:126:in `find_routes'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/journey/router.rb:34:in `serve'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/routing/route_set.rb:896:in `call'](http://localhost:3000/avo/avo_private/status#)
[railties (7.2.2) lib/rails/engine.rb:535:in `call'](http://localhost:3000/avo/avo_private/status#)
[railties (7.2.2) lib/rails/railtie.rb:226:in `public_send'](http://localhost:3000/avo/avo_private/status#)
[railties (7.2.2) lib/rails/railtie.rb:226:in `method_missing'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/routing/mapper.rb:33:in `block in <class:Constraints>'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/routing/mapper.rb:62:in `serve'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/journey/router.rb:53:in `block in serve'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/journey/router.rb:133:in `block in find_routes'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/journey/router.rb:126:in `each'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/journey/router.rb:126:in `find_routes'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/journey/router.rb:34:in `serve'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/routing/route_set.rb:896:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/static.rb:27:in `call'](http://localhost:3000/avo/avo_private/status#)
[bullet (7.2.0) lib/bullet/rack.rb:14:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack (3.1.8) lib/rack/static.rb:161:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack (3.1.8) lib/rack/static.rb:161:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack (3.1.8) lib/rack/static.rb:161:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack (3.1.8) lib/rack/static.rb:161:in `call'](http://localhost:3000/avo/avo_private/status#)
[warden (1.2.9) lib/warden/manager.rb:36:in `block in call'](http://localhost:3000/avo/avo_private/status#)
[warden (1.2.9) lib/warden/manager.rb:34:in `catch'](http://localhost:3000/avo/avo_private/status#)
[warden (1.2.9) lib/warden/manager.rb:34:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack (3.1.8) lib/rack/tempfile_reaper.rb:20:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack (3.1.8) lib/rack/etag.rb:29:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack (3.1.8) lib/rack/conditional_get.rb:31:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack (3.1.8) lib/rack/head.rb:15:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/http/permissions_policy.rb:38:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/http/content_security_policy.rb:35:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'](http://localhost:3000/avo/avo_private/status#)
[rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/cookies.rb:704:in `call'](http://localhost:3000/avo/avo_private/status#)
[activerecord (7.2.2) lib/active_record/migration.rb:674:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/callbacks.rb:101:in `run_callbacks'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/callbacks.rb:30:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/executor.rb:16:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'](http://localhost:3000/avo/avo_private/status#)
[web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'](http://localhost:3000/avo/avo_private/status#)
[web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'](http://localhost:3000/avo/avo_private/status#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'](http://localhost:3000/avo/avo_private/status#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'](http://localhost:3000/avo/avo_private/status#)
[railties (7.2.2) lib/rails/rack/logger.rb:41:in `call_app'](http://localhost:3000/avo/avo_private/status#)
[railties (7.2.2) lib/rails/rack/logger.rb:29:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/remote_ip.rb:96:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/request_id.rb:33:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack (3.1.8) lib/rack/method_override.rb:28:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack (3.1.8) lib/rack/runtime.rb:24:in `call'](http://localhost:3000/avo/avo_private/status#)
[activesupport (7.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/server_timing.rb:60:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/executor.rb:16:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/static.rb:27:in `call'](http://localhost:3000/avo/avo_private/status#)
[rack (3.1.8) lib/rack/sendfile.rb:114:in `call'](http://localhost:3000/avo/avo_private/status#)
[actionpack (7.2.2) lib/action_dispatch/middleware/host_authorization.rb:143:in `call'](http://localhost:3000/avo/avo_private/status#)
[honeybadger (5.19.1) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'](http://localhost:3000/avo/avo_private/status#)
[honeybadger (5.19.1) lib/honeybadger/agent.rb:508:in `with_rack_env'](http://localhost:3000/avo/avo_private/status#)
[honeybadger (5.19.1) lib/honeybadger/rack/error_notifier.rb:30:in `call'](http://localhost:3000/avo/avo_private/status#)
[honeybadger (5.19.1) lib/honeybadger/rack/user_feedback.rb:30:in `call'](http://localhost:3000/avo/avo_private/status#)
[honeybadger (5.19.1) lib/honeybadger/rack/user_informer.rb:20:in `call'](http://localhost:3000/avo/avo_private/status#)
[railties (7.2.2) lib/rails/engine.rb:535:in `call'](http://localhost:3000/avo/avo_private/status#)
[puma (6.4.3) lib/puma/configuration.rb:272:in `call'](http://localhost:3000/avo/avo_private/status#)
[puma (6.4.3) lib/puma/request.rb:100:in `block in handle_request'](http://localhost:3000/avo/avo_private/status#)
[puma (6.4.3) lib/puma/thread_pool.rb:378:in `with_force_shutdown'](http://localhost:3000/avo/avo_private/status#)
[puma (6.4.3) lib/puma/request.rb:99:in `handle_request'](http://localhost:3000/avo/avo_private/status#)
[puma (6.4.3) lib/puma/server.rb:464:in `process_client'](http://localhost:3000/avo/avo_private/status#)
[puma (6.4.3) lib/puma/server.rb:245:in `block in run'](http://localhost:3000/avo/avo_private/status#)
[puma (6.4.3) lib/puma/thread_pool.rb:155:in `block in spawn_thread'](http://localhost:3000/avo/avo_private/status#)
```

**Comment by Paul-Bob** [comment]
@rctneil do you have the avo roles configured?

https://docs.avohq.io/3.0/authentication.html#user-roles

**Comment by adrianthedev** [comment]
I think the fix here is to show the status page even on development even if the roles are not configured.
It shouldn't be there in the first place...

**Comment by rctneil** [comment]
> [@rctneil](https://github.com/rctneil) do you have the avo roles configured?
> 
> https://docs.avohq.io/3.0/authentication.html#user-roles

I don't use roles in this app, so no.
