### ISSUE TITLE
Yarn 4.1.1 support request

### ISSUE THREAD

**Issue by swistaczek** [avo-hq/avo#2620]
I was following [Avo's guide on TailwindCSS integration](https://docs.avohq.io/3.0/tailwindcss-integration); however, after switching to Yarn `4.1.1`, there was an error described below. Everything works as expected with Yarn `1.22.19`.

```
➜  project git:(main) ✗ yarn run avo:tailwindcss

Rebuilding...
Error: Cannot find module 'tailwindcss/plugin'
Require stack:
- /Users/ernest/.rvm/gems/ruby-3.3.0/gems/avo-3.5.4/tailwind.preset.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.resolve (node:internal/modules/cjs/helpers:125:19)
    at _resolve (/Users/ernest/projects/marmot/node_modules/jiti/dist/jiti.js:1:251148)
    at jiti (/Users/ernest/projects/marmot/node_modules/jiti/dist/jiti.js:1:253746)
    at /Users/ernest/.rvm/gems/ruby-3.3.0/gems/avo-3.5.4/tailwind.preset.js:1:91
    at evalModule (/Users/ernest/projects/marmot/node_modules/jiti/dist/jiti.js:1:256443)
    at jiti (/Users/ernest/projects/marmot/node_modules/jiti/dist/jiti.js:1:254371)
    at /Users/ernest/projects/marmot/config/avo/tailwind.config.js:1:94
    at evalModule (/Users/ernest/projects/marmot/node_modules/jiti/dist/jiti.js:1:256443)
    at jiti (/Users/ernest/projects/marmot/node_modules/jiti/dist/jiti.js:1:254371) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ernest/.rvm/gems/ruby-3.3.0/gems/avo-3.5.4/tailwind.preset.js'
  ]
}```

**Comment by adrianthedev** [comment]
Is there a yarn 4?

https://github.com/yarnpkg/yarn/releases

**Comment by swistaczek** [comment]
@adrianthedev As I understand, the repo you pointed to is known as "classic," and current development happens in the [berry project](https://github.com/yarnpkg/berry/releases).

**Comment by adrianthedev** [comment]
Got it!

I'm still travelling for the next few weeks.
Can you use the classic yarn until I get a chance to look it over?

**Comment by swistaczek** [comment]
Hey, maybe bumping issue is not the proper thing but I’d like to avoid closing this one.

**Comment by sedubois** [comment]
I'm curious did you try switching to bun instead of yarn? Any issues?

**Comment by adrianthedev** [comment]
I can't seem to reproduce it on the local repo @swistaczek.

Can you share more details on how you got to that error?

![CleanShot 2024-04-18 at 18 39 26@2x](https://github.com/avo-hq/avo/assets/1334409/4635e2e1-f668-4609-97fd-1812add07cbd)

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen if this pops up again
