### ISSUE TITLE
Setup fails within a `--minimal` Rails app

### ISSUE THREAD

**Issue by simonc** [avo-hq/avo#2686]
### Describe the bug

When running the one-command install, or the manual install, within a Rails app created with the `--minimal` flag, the installation fails with

```
<class:HQ>': undefined method `hours' for an instance of Integer (NoMethodError)
```

### Steps to Reproduce

1. Create a new rails app using `rails new my-app --minimal`
2. `cd my-app`
3. `bundle install`
4. `bin/rails app:template LOCATION='https://avohq.io/app-template'`

### Expected behavior & Actual behavior

I would expect the setup to happen as documented and complete gracefully.

The actual behavior is the error mentioned above with the following trace:

```
$ bin/rails app:template LOCATION='https://avohq.io/app-template'
       apply  https://avohq.io/app-template
     gemfile    avo (>= 3.2)
         run    bundle install from "."
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundle complete! 7 Gemfile dependencies, 78 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run    rails generate avo:install from "."
/Users/simonc/.gem/ruby/3.3.0/gems/avo-3.6.1/lib/avo/licensing/h_q.rb:9:in `<class:HQ>': undefined method `hours' for an instance of Integer (NoMethodError)

      CACHE_TIME = 6.hours.to_i unless const_defined?(:CACHE_TIME) # seconds
                    ^^^^^^
	from /Users/simonc/.gem/ruby/3.3.0/gems/avo-3.6.1/lib/avo/licensing/h_q.rb:3:in `<module:Licensing>'
	from /Users/simonc/.gem/ruby/3.3.0/gems/avo-3.6.1/lib/avo/licensing/h_q.rb:2:in `<module:Avo>'
	from /Users/simonc/.gem/ruby/3.3.0/gems/avo-3.6.1/lib/avo/licensing/h_q.rb:1:in `<top (required)>'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:26:in `require'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:135:in `cget'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:175:in `block in actual_eager_load_dir'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:25:in `each'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:25:in `ls'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:170:in `actual_eager_load_dir'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:16:in `each'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
	from /Users/simonc/.gem/ruby/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
	from /Users/simonc/.gem/ruby/3.3.0/gems/avo-3.6.1/lib/avo.rb:145:in `<top (required)>'
	from <internal:/Users/simonc/.rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/simonc/.rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:55:in `each'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:55:in `block in require'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:44:in `each'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/bundler/runtime.rb:44:in `require'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/bundler.rb:187:in `require'
	from /Users/simonc/Projects/TestAvo/config/application.rb:19:in `<top (required)>'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/simonc/.gem/ruby/3.3.0/gems/railties-7.1.3.2/lib/rails/command/actions.rb:15:in `require_application!'
	from /Users/simonc/.gem/ruby/3.3.0/gems/railties-7.1.3.2/lib/rails/command/actions.rb:19:in `boot_application!'
	from /Users/simonc/.gem/ruby/3.3.0/gems/railties-7.1.3.2/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /Users/simonc/.gem/ruby/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /Users/simonc/.gem/ruby/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/simonc/.gem/ruby/3.3.0/gems/railties-7.1.3.2/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/simonc/.gem/ruby/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /Users/simonc/.gem/ruby/3.3.0/gems/railties-7.1.3.2/lib/rails/command/base.rb:73:in `perform'
	from /Users/simonc/.gem/ruby/3.3.0/gems/railties-7.1.3.2/lib/rails/command.rb:71:in `block in invoke'
	from /Users/simonc/.gem/ruby/3.3.0/gems/railties-7.1.3.2/lib/rails/command.rb:149:in `with_argv'
	from /Users/simonc/.gem/ruby/3.3.0/gems/railties-7.1.3.2/lib/rails/command.rb:69:in `invoke'
	from /Users/simonc/.gem/ruby/3.3.0/gems/railties-7.1.3.2/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/simonc/.rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from bin/rails:4:in `<main>'
         run  bundle install
Bundle complete! 7 Gemfile dependencies, 78 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

### System configuration
**Avo version**:
Latest
**Rails version**: 7.1.3.2
**Ruby version**: 3.3.0

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

---

Also for anyone who lands here in the future, simply uncommenting `require "active_job/railtie"` in `application.rb` loads ActiveSupport and makes it all work.

**Comment by adrianthedev** [comment]
> Also for anyone who lands here in the future, simply uncommenting `require "active_job/railtie"` in `application.rb` loads ActiveSupport and makes it all work.

It seems that's the issue. We use a quite a few things (I suspect) from Active Support.

Thanks for getting back to us with the resolve ❤️
