### ISSUE TITLE
Resource index render fails with "#controller can't be used during initialization" error

### ISSUE THREAD

**Issue by xeron** [avo-hq/avo#2732]
### Describe the bug

After updating `avo` from `3.6.1` to `3.6.2` going into resource index fails with an exception:

```
  Rendered vendor/bundle/ruby/3.1.0/gems/avo-3.6.2/app/views/avo/base/index.html.erb within layouts/avo/blank (Duration: 11.7ms | Allocations: 13192)
  Rendered layout vendor/bundle/ruby/3.1.0/gems/avo-3.6.2/app/views/layouts/avo/blank.html.erb (Duration: 11.8ms | Allocations: 13315)
Completed 500 Internal Server Error in 112ms (ActiveRecord: 30.7ms | Allocations: 118363)

ActionView::Template::Error (`#controller` can't be used during initialization, as it depends on the view context that only exists once a ViewComponent is passed to the Rails render pipeline.

It's sometimes possible to fix this issue by moving code dependent on `#controller` to a [`#before_render` method](https://viewcomponent.org/api.html#before_render--void).):
    1: <%= render Avo::TurboFrameWrapperComponent.new(params[:turbo_frame]) do %>
    2:   <%= render @component.new(
    3:       resource: @resource,
    4:       resources: @resources,
    5:       records: @records,

view_component (3.12.1) lib/view_component/base.rb:216:in `controller'
actionview (7.1.3.2) lib/action_view/helpers/cache_helper.rb:169:in `cache'
actionview (7.1.3.2) lib/action_view/helpers/cache_helper.rb:217:in `cache_if'
avo (3.6.2) app/components/avo/index/resource_table_component.rb:46:in `cache_table_rows'
avo (3.6.2) app/components/avo/index/resource_table_component.rb:16:in `initialize'
avo (3.6.2) app/components/avo/views/resource_index_component.html.erb:56:in `new'
avo (3.6.2) app/components/avo/views/resource_index_component.html.erb:56:in `block (3 levels) in call'
actionview (7.1.3.2) lib/action_view/helpers/capture_helper.rb:50:in `block in capture'
actionview (7.1.3.2) lib/action_view/buffers.rb:75:in `capture'
actionview (7.1.3.2) lib/action_view/helpers/capture_helper.rb:50:in `capture'
view_component (3.12.1) lib/view_component/slot.rb:77:in `to_s'
actionview (7.1.3.2) lib/action_view/buffers.rb:44:in `<<'
avo (3.6.2) app/components/avo/panel_component.html.erb:35:in `block in call'
actionview (7.1.3.2) lib/action_view/helpers/capture_helper.rb:50:in `block in capture'
actionview (7.1.3.2) lib/action_view/buffers.rb:75:in `capture'
actionview (7.1.3.2) lib/action_view/helpers/capture_helper.rb:50:in `capture'
actionview (7.1.3.2) lib/action_view/helpers/tag_helper.rb:349:in `content_tag'
avo (3.6.2) app/components/avo/panel_component.html.erb:1:in `call'
view_component (3.12.1) lib/view_component/compiler.rb:126:in `render_template_for'
view_component (3.12.1) lib/view_component/base.rb:334:in `safe_render_template_for'
view_component (3.12.1) lib/view_component/base.rb:109:in `render_in'
actionview (7.1.3.2) lib/action_view/helpers/rendering_helper.rb:42:in `render'
view_component (3.12.1) lib/view_component/base.rb:205:in `render'
avo (3.6.2) app/components/avo/views/resource_index_component.html.erb:9:in `block in call'
actionview (7.1.3.2) lib/action_view/helpers/capture_helper.rb:50:in `block in capture'
actionview (7.1.3.2) lib/action_view/buffers.rb:75:in `capture'
actionview (7.1.3.2) lib/action_view/helpers/capture_helper.rb:50:in `capture'
actionview (7.1.3.2) lib/action_view/helpers/tag_helper.rb:349:in `content_tag'
avo (3.6.2) app/components/avo/views/resource_index_component.html.erb:1:in `call'
view_component (3.12.1) lib/view_component/compiler.rb:126:in `render_template_for'
view_component (3.12.1) lib/view_component/base.rb:334:in `safe_render_template_for'
view_component (3.12.1) lib/view_component/base.rb:109:in `render_in'
actionview (7.1.3.2) lib/action_view/helpers/rendering_helper.rb:42:in `render'
avo (3.6.2) app/views/avo/base/index.html.erb:2
actionview (7.1.3.2) lib/action_view/helpers/capture_helper.rb:50:in `block in capture'
actionview (7.1.3.2) lib/action_view/buffers.rb:75:in `capture'
actionview (7.1.3.2) lib/action_view/helpers/capture_helper.rb:50:in `capture'
view_component (3.12.1) lib/view_component/base.rb:291:in `content'
avo (3.6.2) app/components/avo/turbo_frame_wrapper_component.html.erb:9:in `call'
view_component (3.12.1) lib/view_component/compiler.rb:126:in `render_template_for'
view_component (3.12.1) lib/view_component/base.rb:334:in `safe_render_template_for'
view_component (3.12.1) lib/view_component/base.rb:109:in `render_in'
actionview (7.1.3.2) lib/action_view/helpers/rendering_helper.rb:42:in `render'
avo (3.6.2) app/views/avo/base/index.html.erb:1
```

`show` and `edit` actions work. `index` doesn't.

Rolling back to `3.6.1` fixes the issue.

### Steps to Reproduce

1. Add avo resource
2. Go to resource index
3. See error

### Expected behavior & Actual behavior

Resource index rendered without a error.

### Models and resource files

The simplest resource I have which still fails:

```
class Avo::Resources::Tire < Avo::BaseResource
  self.title = :name
  self.includes = []
  self.record_selector = false

  self.search = {
    query: lambda {
      query.ransack(
        name_cont: params[:q], m: 'or'
      ).result(distinct: true)
    }
  }

  def fields
    field :name, as: :text

    field :results, as: :has_many
  end
end
```

### System configuration

**Avo version**: 3.6.2
**Rails version**: 7.1.3.2
**Ruby version**: 3.1.5
**License type**:
 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

N/A

### Additional context

N/A

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by sedubois** [comment]
I had also raised this issue in discord - https://discord.com/channels/740892036978442260/1125160641569771550/1231172900535668736

**Comment by Paul-Bob** [comment]
Working on a patch to fix it, `config.cache_resources_on_index_view = false` should avoid the error until the patch is released

**Comment by Paul-Bob** [comment]
@xeron & @sedubois this issue should be fixed on the `3.6.3` fresh release. Thanks for reporting it

**Comment by xeron** [comment]
@Paul-Bob I'm seeing new error in production now. For some reason I don't see it locally or in staging:

```
I, [2024-05-01T19:00:35.859981 #3849155]  INFO -- sentry: [Transport] Sending envelope with items [transaction] 4f0456bde1a94bbea2e04e6a400ea01c to Sentry
I, [2024-05-01T19:00:36.045204 #3849159]  INFO -- : [6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0] Started GET "/admin/resources/car_classes" for 162.158.78.97 at 2024-05-01 19:00:36 +0000
I, [2024-05-01T19:00:36.047198 #3849159]  INFO -- : [6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0] Processing by Avo::CarClassesController#index as HTML
I, [2024-05-01T19:00:36.073354 #3849159]  INFO -- : [6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0]   Rendered layout /home/webmaster/www/86dc-production/shared/bundle/ruby/3.1.0/gems/avo-3.6.3/app/views/layouts/avo/application.html.erb (Duration: 7.2ms | Allocations: 4420)
I, [2024-05-01T19:00:36.073743 #3849159]  INFO -- : [6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0] Completed 500 Internal Server Error in 26ms (ActiveRecord: 3.5ms | Allocations: 12670)
E, [2024-05-01T19:00:36.077841 #3849159] ERROR -- : [6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0]
[6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0] ActionView::Template::Error (undefined method `each_with_index' for nil:NilClass):
[6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0]     17:       <!-- Item controls cell -->
[6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0]     18:     </th>
[6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0]     19:   <% end %>
[6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0]     20:   <% fields.each_with_index do |field, index|  %>
[6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0]     21:     <%
[6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0]     22:       if params[:sort_by] == field.id.to_s
[6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0]     23:         if params[:sort_direction] == 'asc'
[6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0]
[6884ec6f-4bf6-4e3b-8ae6-6139c76d9ca0] avo (3.6.3) app/views/avo/partials/_table_header.html.erb:20
```

**Comment by Paul-Bob** [comment]
@xeron `3.6.4` includes a fix for this last issue. [You should clear production cache after release. `Rails.cache.clear`](https://docs.avohq.io/3.0/upgrade.html#cache)

Can you confirm please?

**Comment by xeron** [comment]
> Can you confirm please?

Seems like it's working now. Thanks!
