### ISSUE TITLE
undefined method `remove_scope_all' for nil

### ISSUE THREAD

**Issue by smathieu** [avo-hq/avo#3293]
### Describe the bug
When updating to Avo 3.13.0, we're getting this error when the app boots.

```
Showing /Users/smathieu/.gem/ruby/3.3.0/gems/avo-3.13.0/app/views/avo/base/index.html.erb where line #2 raised:

undefined method `remove_scope_all' for nil
```

<details>
  <summary>stacktrace</summary>
```
[avo-advanced (3.10.6) app/components/avo/advanced/scopes/list_component.rb:14:in `initialize'](https://tangible-api.com/admin/resources/catalog_products#)
[avo (3.13.0) app/components/avo/views/resource_index_component.rb:164:in `new'](https://tangible-api.com/admin/resources/catalog_products#)
[avo (3.13.0) app/components/avo/views/resource_index_component.rb:164:in `scopes_list'](https://tangible-api.com/admin/resources/catalog_products#)
[avo (3.13.0) app/components/avo/views/resource_index_component.html.erb:34:in `block (3 levels) in call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/capture_helper.rb:50:in `block in capture'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/buffers.rb:75:in `capture'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/capture_helper.rb:50:in `capture'](https://tangible-api.com/admin/resources/catalog_products#)
[view_component (3.15.1) lib/view_component/slot.rb:77:in `to_s'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/buffers.rb:44:in `<<'](https://tangible-api.com/admin/resources/catalog_products#)
[avo (3.13.0) app/components/avo/panel_component.html.erb:42:in `block in call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/capture_helper.rb:50:in `block in capture'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/buffers.rb:75:in `capture'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/capture_helper.rb:50:in `capture'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/tag_helper.rb:534:in `content_tag'](https://tangible-api.com/admin/resources/catalog_products#)
[avo (3.13.0) app/components/avo/panel_component.html.erb:1:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[view_component (3.15.1) lib/view_component/compiler.rb:95:in `render_template_for'](https://tangible-api.com/admin/resources/catalog_products#)
[view_component (3.15.1) lib/view_component/base.rb:113:in `render_in'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/rendering_helper.rb:42:in `render'](https://tangible-api.com/admin/resources/catalog_products#)
[view_component (3.15.1) lib/view_component/base.rb:215:in `render'](https://tangible-api.com/admin/resources/catalog_products#)
[avo (3.13.0) app/components/avo/views/resource_index_component.html.erb:10:in `block in call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/capture_helper.rb:50:in `block in capture'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/buffers.rb:75:in `capture'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/capture_helper.rb:50:in `capture'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/tag_helper.rb:534:in `content_tag'](https://tangible-api.com/admin/resources/catalog_products#)
[avo (3.13.0) app/components/avo/views/resource_index_component.html.erb:1:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[view_component (3.15.1) lib/view_component/compiler.rb:95:in `render_template_for'](https://tangible-api.com/admin/resources/catalog_products#)
[view_component (3.15.1) lib/view_component/base.rb:113:in `render_in'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/rendering_helper.rb:42:in `render'](https://tangible-api.com/admin/resources/catalog_products#)
[avo (3.13.0) app/views/avo/base/index.html.erb:2](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/capture_helper.rb:50:in `block in capture'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/buffers.rb:75:in `capture'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/capture_helper.rb:50:in `capture'](https://tangible-api.com/admin/resources/catalog_products#)
[view_component (3.15.1) lib/view_component/base.rb:301:in `content'](https://tangible-api.com/admin/resources/catalog_products#)
[avo (3.13.0) app/components/avo/turbo_frame_wrapper_component.html.erb:9:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[view_component (3.15.1) lib/view_component/compiler.rb:95:in `render_template_for'](https://tangible-api.com/admin/resources/catalog_products#)
[view_component (3.15.1) lib/view_component/base.rb:113:in `render_in'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/helpers/rendering_helper.rb:42:in `render'](https://tangible-api.com/admin/resources/catalog_products#)
[avo (3.13.0) app/views/avo/base/index.html.erb:1](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/base.rb:281:in `public_send'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/base.rb:281:in `_run'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/template.rb:275:in `block in render'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications.rb:210:in `block in instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications/instrumenter.rb:58:in `instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications.rb:210:in `instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/template.rb:574:in `instrument_render_template'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/template.rb:263:in `render'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:66:in `block (2 levels) in render_template'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications.rb:210:in `block in instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications/instrumenter.rb:58:in `instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications.rb:210:in `instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:76:in `block in render_with_layout'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications.rb:210:in `block in instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications/instrumenter.rb:58:in `instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications.rb:210:in `instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:75:in `render_with_layout'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:59:in `render_template'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/renderer/template_renderer.rb:11:in `render'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/renderer/renderer.rb:58:in `render_template_to_object'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/renderer/renderer.rb:31:in `render_to_object'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/rendering.rb:135:in `block in _render_template'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/base.rb:308:in `in_rendering_context'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/rendering.rb:134:in `_render_template'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/streaming.rb:258:in `_render_template'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/rendering.rb:121:in `render_to_body'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/rendering.rb:186:in `render_to_body'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/abstract_controller/rendering.rb:29:in `render'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/rendering.rb:167:in `render'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block (2 levels) in render'](https://tangible-api.com/admin/resources/catalog_products#)
[/Users/smathieu/.rubies/ruby-3.3.0/lib/ruby/3.3.0/benchmark.rb:313:in `realtime'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in render'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:101:in `cleanup_view_runtime'](https://tangible-api.com/admin/resources/catalog_products#)
[activerecord (7.2.1) lib/active_record/railties/controller_runtime.rb:46:in `cleanup_view_runtime'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:31:in `render'](https://tangible-api.com/admin/resources/catalog_products#)
[meta-tags (2.22.1) lib/meta_tags/controller_helper.rb:22:in `render'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/implicit_render.rb:39:in `default_render'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/basic_implicit_render.rb:9:in `send_action'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/abstract_controller/base.rb:226:in `process_action'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/rendering.rb:193:in `process_action'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/abstract_controller/callbacks.rb:261:in `block in process_action'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/tagged_logging.rb:138:in `block in tagged'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/tagged_logging.rb:38:in `tagged'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/tagged_logging.rb:138:in `tagged'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/broadcast_logger.rb:241:in `method_missing'](https://tangible-api.com/admin/resources/catalog_products#)
[app/models/actor.rb:44:in `with'](https://tangible-api.com/admin/resources/catalog_products#)
[app/controllers/concerns/controller_with_actor.rb:11:in `with_actor'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'](https://tangible-api.com/admin/resources/catalog_products#)
[i18n (1.14.6) lib/i18n.rb:353:in `with_locale'](https://tangible-api.com/admin/resources/catalog_products#)
[avo (3.13.0) app/controllers/avo/application_controller.rb:287:in `set_avo_locale'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'](https://tangible-api.com/admin/resources/catalog_products#)
[turbo-rails (2.0.10) lib/turbo-rails.rb:24:in `with_request_id'](https://tangible-api.com/admin/resources/catalog_products#)
[turbo-rails (2.0.10) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-rails (5.20.1) lib/sentry/rails/controller_transaction.rb:30:in `block in sentry_around_action'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-ruby (5.20.1) lib/sentry/hub.rb:108:in `with_child_span'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-ruby (5.20.1) lib/sentry-ruby.rb:498:in `with_child_span'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-rails (5.20.1) lib/sentry/rails/controller_transaction.rb:16:in `sentry_around_action'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/callbacks.rb:130:in `block in run_callbacks'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/callbacks.rb:141:in `run_callbacks'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/abstract_controller/callbacks.rb:260:in `process_action'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/rescue.rb:27:in `process_action'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:77:in `block in process_action'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications.rb:210:in `block in instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications/instrumenter.rb:58:in `instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/notifications.rb:210:in `instrument'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/instrumentation.rb:76:in `process_action'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'](https://tangible-api.com/admin/resources/catalog_products#)
[activerecord (7.2.1) lib/active_record/railties/controller_runtime.rb:39:in `process_action'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/abstract_controller/base.rb:163:in `process'](https://tangible-api.com/admin/resources/catalog_products#)
[actionview (7.2.1) lib/action_view/rendering.rb:40:in `process'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal.rb:252:in `dispatch'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_controller/metal.rb:335:in `dispatch'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/routing/route_set.rb:67:in `dispatch'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/routing/route_set.rb:50:in `serve'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/journey/router.rb:53:in `block in serve'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/journey/router.rb:133:in `block in find_routes'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/journey/router.rb:126:in `each'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/journey/router.rb:126:in `find_routes'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/journey/router.rb:34:in `serve'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/routing/route_set.rb:896:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[railties (7.2.1) lib/rails/engine.rb:535:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[railties (7.2.1) lib/rails/railtie.rb:226:in `public_send'](https://tangible-api.com/admin/resources/catalog_products#)
[railties (7.2.1) lib/rails/railtie.rb:226:in `method_missing'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/routing/mapper.rb:33:in `block in <class:Constraints>'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/routing/mapper.rb:62:in `serve'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/journey/router.rb:53:in `block in serve'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/journey/router.rb:133:in `block in find_routes'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/journey/router.rb:126:in `each'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/journey/router.rb:126:in `find_routes'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/journey/router.rb:34:in `serve'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/routing/route_set.rb:896:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/static.rb:27:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[omniauth (2.1.2) lib/omniauth/strategy.rb:470:in `call_app!'](https://tangible-api.com/admin/resources/catalog_products#)
[omniauth-saml (2.2.1) lib/omniauth/strategies/saml.rb:86:in `other_phase'](https://tangible-api.com/admin/resources/catalog_products#)
[omniauth (2.1.2) lib/omniauth/strategy.rb:195:in `call!'](https://tangible-api.com/admin/resources/catalog_products#)
[omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'](https://tangible-api.com/admin/resources/catalog_products#)
[omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'](https://tangible-api.com/admin/resources/catalog_products#)
[omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[omniauth (2.1.2) lib/omniauth/builder.rb:44:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[scout_apm (5.4.0) lib/scout_apm/instant/middleware.rb:55:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[scout_apm (5.4.0) lib/scout_apm/middleware.rb:20:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[warden-jwt_auth (0.10.0) lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[warden-jwt_auth (0.10.0) lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/builder.rb:244:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[warden-jwt_auth (0.10.0) lib/warden/jwt_auth/middleware.rb:22:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[warden (1.2.9) lib/warden/manager.rb:36:in `block in call'](https://tangible-api.com/admin/resources/catalog_products#)
[warden (1.2.9) lib/warden/manager.rb:34:in `catch'](https://tangible-api.com/admin/resources/catalog_products#)
[warden (1.2.9) lib/warden/manager.rb:34:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/static.rb:161:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/static.rb:161:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/static.rb:161:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/static.rb:161:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/tempfile_reaper.rb:15:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/etag.rb:27:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/conditional_get.rb:27:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/head.rb:12:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/http/permissions_policy.rb:38:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/http/content_security_policy.rb:36:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/session/abstract/id.rb:266:in `context'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/session/abstract/id.rb:260:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/cookies.rb:704:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[activerecord (7.2.1) lib/active_record/migration.rb:674:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/callbacks.rb:101:in `run_callbacks'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/callbacks.rb:30:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/executor.rb:16:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-rails (5.20.1) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'](https://tangible-api.com/admin/resources/catalog_products#)
[web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'](https://tangible-api.com/admin/resources/catalog_products#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'](https://tangible-api.com/admin/resources/catalog_products#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-ruby (5.20.1) lib/sentry/rack/capture_exceptions.rb:30:in `block (2 levels) in call'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-ruby (5.20.1) lib/sentry/hub.rb:265:in `with_session_tracking'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-ruby (5.20.1) lib/sentry-ruby.rb:411:in `with_session_tracking'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-ruby (5.20.1) lib/sentry/rack/capture_exceptions.rb:21:in `block in call'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-ruby (5.20.1) lib/sentry/hub.rb:59:in `with_scope'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-ruby (5.20.1) lib/sentry-ruby.rb:391:in `with_scope'](https://tangible-api.com/admin/resources/catalog_products#)
[sentry-ruby (5.20.1) lib/sentry/rack/capture_exceptions.rb:20:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[railties (7.2.1) lib/rails/rack/logger.rb:41:in `call_app'](https://tangible-api.com/admin/resources/catalog_products#)
[railties (7.2.1) lib/rails/rack/logger.rb:29:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/remote_ip.rb:96:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/request_id.rb:33:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/method_override.rb:24:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/runtime.rb:22:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[judoscale-ruby (1.8.1) lib/judoscale/request_middleware.rb:41:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[activesupport (7.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/server_timing.rb:60:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/executor.rb:16:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/static.rb:27:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack (2.2.9) lib/rack/sendfile.rb:110:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[actionpack (7.2.1) lib/action_dispatch/middleware/host_authorization.rb:143:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack-mini-profiler (3.3.1) lib/mini_profiler.rb:334:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[rack-cors (2.0.2) lib/rack/cors.rb:102:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[railties (7.2.1) lib/rails/engine.rb:535:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[puma (6.4.3) lib/puma/configuration.rb:272:in `call'](https://tangible-api.com/admin/resources/catalog_products#)
[puma (6.4.3) lib/puma/request.rb:100:in `block in handle_request'](https://tangible-api.com/admin/resources/catalog_products#)
[puma (6.4.3) lib/puma/thread_pool.rb:378:in `with_force_shutdown'](https://tangible-api.com/admin/resources/catalog_products#)
[puma (6.4.3) lib/puma/request.rb:99:in `handle_request'](https://tangible-api.com/admin/resources/catalog_products#)
[puma (6.4.3) lib/puma/server.rb:464:in `process_client'](https://tangible-api.com/admin/resources/catalog_products#)
[puma (6.4.3) lib/puma/server.rb:245:in `block in run'](https://tangible-api.com/admin/resources/catalog_products#)
[puma (6.4.3) lib/puma/thread_pool.rb:155:in `block in spawn_thread'](https://tangible-api.com/admin/resources/catalog_products#)
``` 
</details>

### Steps to Reproduce
1. Add this configuration '...'
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

### Models and resource files

We use `remove_scope_all` in a few places like so:

```ruby
module Avo
  module Resources
    class OurClass < Avo::BaseResource
      self.includes = []

      def scopes
        remove_scope_all
        scope Avo::Scopes::OurScope1
        scope Avo::Scopes::OurScope2
      end
```

### System configuration
**Avo version**: 3.13.0 

**Rails version**:7.2.1

**Ruby version**: 3.3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

Can't upgrade Avo

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hello @smathieu I'm not able to reproduce it.

Can you please share the output for `bundle info avo-advanced`?

**Comment by smathieu** [comment]
* avo-advanced (3.10.6)
	Summary: Avo advanced package
	Homepage: https://github.com/avo-hq/avo
	Path: /Users/smathieu/.gem/ruby/3.3.0/gems/avo-advanced-3.10.6

**Comment by Paul-Bob** [comment]
That's it, your Avo gems are out of sync.

Please use `rails avo:update` to update Avo, that task will ensure sync along all the packages.

When Avo is `3.13.0` all other gems like `avo-advanced` should also be `3.13.0`

**Comment by smathieu** [comment]
No luck.

```
➜ tangible-api (dependabot/bundler/avo-e73e179aa8) ./bin/rails avo:update
warning: parser/current is loading parser/ruby33, which recognizes 3.3.5-compliant syntax, but you are running 3.3.0.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Fetching https://github.com/saltlabsinc/ransack.git
Fetching gem metadata from https://gems.contribsys.com/..
Fetching gem metadata from https://packager.dev/avo-hq/...
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Installing view_component 3.16.0 (was 3.15.1)
Installing avo 3.13.1 (was 3.13.0)
Installing avo-dashboards 3.13.1 (was 3.13.0)
Installing avo-menu 3.13.1 (was 3.13.0)
Installing avo-pro 3.13.1 (was 3.13.0)
Bundle updated!
Post-install message from avo:
Thank you for using Avo 💪  Docs are available at https://docs.avohq.io
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
➜ tangible-api (dependabot/bundler/avo-e73e179aa8) ✗ bundle info avo-advanced
  * avo-advanced (3.10.6)
	Summary: Avo advanced package
	Homepage: https://github.com/avo-hq/avo
	Path: /Users/smathieu/.gem/ruby/3.3.0/gems/avo-advanced-3.10.6
```

Our Gemfile doesn't pin the version as far as I can see.

```
gem "avo"
gem "avo-advanced", source: "https://packager.dev/avo-hq/"
gem "avo-pro", source: "https://packager.dev/avo-hq/"
```

**Comment by Paul-Bob** [comment]
Do you have a lock on `ransak`?

`avo-dynamic-filters` depend on `"ransack", ">= 4.2.0"` And if you have a lower version locked, it will not update, and for some reason, the bundle doesn't warn about these scenarios.

If this is the case `avo-dynamic-filters` is blocking the `avo-advanced` to update.

**Comment by smathieu** [comment]
Ah, yes, `ransack` was pinned to a specific branch to address a bug that is now fixed in the latest version. Removing the pinning fixed the issue for us. Thanks for you support here.
