### ISSUE TITLE
License check throwing spurious errors

### ISSUE THREAD

**Issue by brittlewis12** [avo-hq/avo#3321]
### Describe the bug

Hi there folks! We've been experiencing exceptions from license checks affecting our staging & production environments every few navigation requests to the admin app. We've seen 60+ error events in last 2 days with very light usage.

```
/app/vendor/bundle/ruby/3.3.0/gems/avo-3.11.10/lib/avo/licensing/license_manager.rb:9:in `license`: undefined method `[]` for nil (NoMethodError)
```

### Steps to Reproduce
1. visit avo admin root (both staging and production)
1. navigate to a resource
1. see something went wrong/internal server error message (500)
1. reload may or may not succeed after waiting a few moments

### Expected behavior & Actual behavior

- **expected**: Intermittent failed requests to license check should not have a negative impact on application behavior. More graceful degradation.
- **actual**: Exceptions are preventing admins from using the avo-powered admin functionality.

### System configuration
**Avo version**: 3.11.10

**Rails version**: 7.2.1

**Ruby version**: 3.3.4

**License type**:

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Additional context

- We have allowlisted both our production and our staging domains in the avohq web dashboard.
- We have disabled avo cache.
- Licensed account public key: `894fe4e1eab`
<details><summary>full stacktrace</summary>

```
/app/vendor/bundle/ruby/3.3.0/gems/avo-3.11.10/lib/avo/licensing/license_manager.rb:9:in `license': undefined method `[]' for nil (NoMethodError)
	from /app/vendor/bundle/ruby/3.3.0/gems/avo-3.11.10/app/controllers/concerns/avo/initializes_avo.rb:9:in `init_app'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:362:in `block in make_lambda'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:179:in `block in call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:180:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `block in invoke_before'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `each'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `invoke_before'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:119:in `block in run_callbacks'
	from /app/vendor/bundle/ruby/3.3.0/gems/i18n-1.14.5/lib/i18n.rb:351:in `with_locale'
	from /app/vendor/bundle/ruby/3.3.0/gems/avo-3.11.10/app/controllers/avo/application_controller.rb:286:in `set_avo_locale'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
	from /app/vendor/bundle/ruby/3.3.0/gems/turbo-rails-2.0.6/lib/turbo-rails.rb:24:in `with_request_id'
	from /app/vendor/bundle/ruby/3.3.0/gems/turbo-rails-2.0.6/app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
	from /app/vendor/bundle/ruby/3.3.0/gems/actiontext-7.2.1/lib/action_text/rendering.rb:25:in `with_renderer'
	from /app/vendor/bundle/ruby/3.3.0/gems/actiontext-7.2.1/lib/action_text/engine.rb:71:in `block (4 levels) in <class:Engine>'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:130:in `instance_exec'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:141:in `run_callbacks'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/abstract_controller/callbacks.rb:260:in `process_action'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_controller/metal/rescue.rb:27:in `process_action'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_controller/metal/instrumentation.rb:77:in `block in process_action'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/notifications.rb:210:in `block in instrument'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/notifications.rb:210:in `instrument'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_controller/metal/instrumentation.rb:76:in `process_action'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
	from /app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.2.1/lib/active_record/railties/controller_runtime.rb:39:in `process_action'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/abstract_controller/base.rb:163:in `process'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionview-7.2.1/lib/action_view/rendering.rb:40:in `process'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_controller/metal.rb:252:in `dispatch'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_controller/metal.rb:335:in `dispatch'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/routing/route_set.rb:67:in `dispatch'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/routing/route_set.rb:50:in `serve'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/journey/router.rb:53:in `block in serve'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/journey/router.rb:133:in `block in find_routes'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/journey/router.rb:126:in `each'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/journey/router.rb:126:in `find_routes'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/journey/router.rb:34:in `serve'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/routing/route_set.rb:896:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/engine.rb:535:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/railtie.rb:226:in `public_send'
	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/railtie.rb:226:in `method_missing'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/routing/mapper.rb:33:in `block in <class:Constraints>'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/routing/mapper.rb:62:in `serve'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/journey/router.rb:53:in `block in serve'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/journey/router.rb:133:in `block in find_routes'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/journey/router.rb:126:in `each'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/journey/router.rb:126:in `find_routes'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/journey/router.rb:34:in `serve'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/routing/route_set.rb:896:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/static.rb:161:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/static.rb:161:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/static.rb:161:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/tempfile_reaper.rb:20:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/etag.rb:29:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/conditional_get.rb:31:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/head.rb:15:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:272:in `context'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-session-2.0.0/lib/rack/session/abstract/id.rb:266:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/cookies.rb:704:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'
	from /app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/callbacks.rb:30:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing/contrib/rails/middlewares.rb:19:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/rack/logger.rb:41:in `call_app'
	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/rack/logger.rb:29:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/request_id.rb:33:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/method_override.rb:28:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/runtime.rb:24:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/executor.rb:16:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/static.rb:27:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/rack-3.1.7/lib/rack/sendfile.rb:114:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.1/lib/action_dispatch/middleware/ssl.rb:82:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing/contrib/rack/middlewares.rb:70:in `block in call'
	from /app/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing/contrib/rack/trace_proxy_middleware.rb:17:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing/contrib/rack/middlewares.rb:49:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.1/lib/rails/engine.rb:535:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/configuration.rb:272:in `call'
	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/request.rb:100:in `block in handle_request'
	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/request.rb:99:in `handle_request'
	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/server.rb:464:in `process_client'
	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/server.rb:245:in `block in run'
	from /app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.3/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

</details>

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Hey @brittlewis12.


We updated one of our monitoring libraries and haven't updated the implementation on our side.
This caused issues in the error catching mechanism.
We have a lot of failsafes in place so these things (errors on our side) don't impact the apps that use Avo.

It should be fixed now. 
Apologies for the issues and thanks for reporting it.

**Comment by brittlewis12** [comment]
@adrianthedev thanks very much for jumping on this so promptly!

**Comment by adrianthedev** [comment]
No, of course!
This is priority 0 (the highest) for us. 

Thanks for reporting it!

PS: I wrote this last week but failed to send the comment 🤦‍♂️
