### ISSUE TITLE
Rhino field doesn't work

### ISSUE THREAD

**Issue by SahSantoshh** [avo-hq/avo#3460]
### Describe the bug
I upgraded my app to latest avo (3.4.1) and wanted to try the new `rhino` field type and It didn't show on the page.

### Steps to Reproduce
1. Go to any resource whose attribute is set as `text` for long text
2. Change `text` to `rhino`
3. Try to edit or create new record
4. Either it won't show the field or show an error

### Expected behavior & Actual behavior
I should work as it's mentioned [here](https://github.com/avo-hq/main.avodemo.com/blob/ddb2dcb47d5456eebd4378f42315b58d08ac27ba/app/avo/resources/post.rb#L32)

### Models and resource files
In Demo app `Posts` in reproducible repo `Products`

### System configuration
**Avo version**: 3.14.3

**Rails version**: 7.2.0

**Ruby version**: 3.3.0

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
![Image](https://github.com/user-attachments/assets/cc53ef26-cc33-4fbc-bb1b-7008e36493f5)

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [x] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment]
Hi @SahSantoshh could you please also upgrade the rhino field and verify if the issue persists? `bundle update avo-rhino_field`

**Comment by SahSantoshh** [comment]
Now, not able to run the app,
logs
```shell
19:41:42 web.1     | started with pid 55935
19:41:42 css.1     | started with pid 55936
19:41:42 avo_css.1 | started with pid 55937
19:41:42 avo_css.1 | yarn run v1.22.21
19:41:42 avo_css.1 | $ tailwindcss -i ./app/assets/stylesheets/avo/avo.tailwind.css -o ./app/assets/builds/avo.tailwind.css -c ./config/avo/tailwind.config.js --minify --watch
19:41:43 web.1     | DEPRECATION WARNING: ActiveSupport::ProxyObject is deprecated and will be removed in Rails 8.0.
19:41:43 web.1     | Use Ruby's built-in BasicObject instead.
19:41:43 web.1     |  (called from <main> at /Users/sahsantoshh/Documents/SelectIT/finance_crm/config/application.rb:19)
19:41:43 web.1     | DEPRECATION WARNING: ActiveSupport::ProxyObject is deprecated and will be removed in Rails 8.0.
19:41:43 web.1     | Use Ruby's built-in BasicObject instead.
19:41:43 web.1     |  (called from <main> at /Users/sahsantoshh/Documents/SelectIT/finance_crm/config/application.rb:19)
19:41:43 css.1     | DEPRECATION WARNING: ActiveSupport::ProxyObject is deprecated and will be removed in Rails 8.0.
19:41:43 css.1     | Use Ruby's built-in BasicObject instead.
19:41:43 css.1     |  (called from <main> at /Users/sahsantoshh/Documents/SelectIT/finance_crm/config/application.rb:19)
19:41:43 css.1     | DEPRECATION WARNING: ActiveSupport::ProxyObject is deprecated and will be removed in Rails 8.0.
19:41:43 css.1     | Use Ruby's built-in BasicObject instead.
19:41:43 css.1     |  (called from <main> at /Users/sahsantoshh/Documents/SelectIT/finance_crm/config/application.rb:19)
19:41:43 web.1     | => Booting Puma
19:41:43 web.1     | => Rails 7.2.0 application starting in development 
19:41:43 web.1     | => Run `bin/rails server --help` for more startup options
19:41:43 avo_css.1 | 
19:41:43 avo_css.1 | Rebuilding...
19:41:43 css.1     | bin/rails aborted!
19:41:43 web.1     | Exiting
19:41:43 css.1     | NoMethodError: undefined method `field_name_attribute=' for module Avo::Fields::RhinoField (NoMethodError)
19:41:43 css.1     | 
19:41:43 css.1     |       klass.field_name_attribute = method_name
19:41:43 web.1     | /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/avo-3.14.3/lib/avo/plugin_manager.rb:21:in `register_field': undefined method `field_name_attribute=' for module Avo::Fields::RhinoField (NoMethodError)
19:41:43 css.1     |            ^^^^^^^^^^^^^^^^^^^^^^^
19:41:43 web.1     | 
19:41:43 css.1     | /Users/sahsantoshh/Documents/SelectIT/finance_crm/config/environment.rb:5:in `<main>'
19:41:43 web.1     |       klass.field_name_attribute = method_name
19:41:43 css.1     | Tasks: TOP => tailwindcss:watch => environment
19:41:43 web.1     |            ^^^^^^^^^^^^^^^^^^^^^^^
19:41:43 css.1     | (See full trace by running task with --trace)
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/avo-rhino_field-0.0.11/lib/avo/rhino_field/engine.rb:12:in `block (2 levels) in <class:Engine>'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/lazy_load_hooks.rb:77:in `each'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/avo-3.14.3/lib/avo.rb:66:in `boot'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/avo-3.14.3/lib/avo/engine.rb:45:in `block in <class:Engine>'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:407:in `instance_exec'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:407:in `block in make_lambda'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:179:in `block in call'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:668:in `block (2 levels) in default_terminator'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:667:in `catch'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:667:in `block in default_terminator'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:180:in `call'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:559:in `block in invoke_before'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:559:in `each'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:559:in `invoke_before'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/callbacks.rb:109:in `run_callbacks'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activesupport-7.2.0/lib/active_support/reloader.rb:96:in `prepare!'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/initializable.rb:32:in `instance_exec'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/initializable.rb:32:in `run'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/tsort.rb:350:in `each'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/tsort.rb:350:in `call'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/initializable.rb:60:in `run_initializers'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/application.rb:428:in `initialize!'
19:41:43 web.1     | 	from /Users/sahsantoshh/Documents/SelectIT/finance_crm/config/environment.rb:5:in `<main>'
19:41:43 web.1     | 	from config.ru:3:in `require_relative'
19:41:43 web.1     | 	from config.ru:3:in `block (2 levels) in <main>'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:108:in `eval'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:108:in `new_from_string'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:97:in `load_file'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:67:in `parse_file'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:263:in `app'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:424:in `wrapped_app'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands/server/server_command.rb:36:in `start'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands/server/server_command.rb:145:in `block in perform'
19:41:43 web.1     | 	from <internal:kernel>:90:in `tap'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands/server/server_command.rb:136:in `perform'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command/base.rb:178:in `invoke_command'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command/base.rb:73:in `perform'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:71:in `block in invoke'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:149:in `with_argv'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/command.rb:69:in `invoke'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/railties-7.2.0/lib/rails/commands.rb:18:in `<main>'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
19:41:43 web.1     | 	from /Users/sahsantoshh/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
19:41:43 web.1     | 	from bin/rails:4:in `<main>'
19:41:43 css.1     | exited with code 1
19:41:43 system    | sending SIGTERM to all processes
19:41:43 web.1     | exited with code 1
19:41:43 avo_css.1 | exited with code 1
```

**Comment by SahSantoshh** [comment]
Reproducible repo https://github.com/SahSantoshh/avo_search

**Comment by Paul-Bob** [comment]
Hi @SahSantoshh thanks for the reproduction repo!

Just pushed a new version on `avo-rhino_field` which should be fixing this issue.

Closing as completed, feel free to continue the discussion or reopen this if the issue persists.
