### ISSUE TITLE
Avo issues with logger gem

### ISSUE THREAD

**Issue by aldent95** [avo-hq/avo#3560]
### Describe the bug
Avo prevents a Rails application from being launched with logger gem version 1.6.3 or higher

### Reproduction repository for the bug
Can be reproduced from a fresh rails app made using the following rails new command (Change the directory for your system) ```rails _8.0.1_ new D:/Dev/Test --javascript=importmap --skip --database=sqlite3```

### Steps to use in the reproduction repository
- Create a new Rails app with rails new
- Install Avo
- Pin logger to version 1.6.3 or higher
- Run bundle install
- Attempt to start the rails app (Or even run rake tasks or generators)
- Observe ```Uncaught exception: no implicit conversion of Pathname into String``` error
- Ping logger to version 1.6.2
- Run bundle install
- Rerun the app and observe no error

### Expected behavior & Actual behavior
Expected: Rails should run fine

Actual: 
```
=> Booting Puma
=> Rails 8.0.0 application starting in development
=> Run `bin/rails server --help` for more startup options
Exiting
Uncaught exception: no implicit conversion of Pathname into String
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:99:in `initialize'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:99:in `new'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:99:in `fixup_mode'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:112:in `open_logfile'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:85:in `set_dev'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:19:in `initialize'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger.rb:593:in `new'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger.rb:593:in `initialize'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/logger.rb:34:in `initialize'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/configuration.rb:237:in `new'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/configuration.rb:237:in `block in default_logger'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/execution_context.rb:41:in `instance_exec'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/execution_context.rb:41:in `handle'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/configuration.rb:232:in `logger'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo.rb:64:in `boot'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/engine.rb:45:in `block in <class:Engine>'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:406:in `instance_exec'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:406:in `block in make_lambda'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:178:in `block in call'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:667:in `block (2 levels) in default_terminator'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:666:in `catch'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:666:in `block in default_terminator'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:179:in `call'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:558:in `block in invoke_before'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:558:in `each'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:558:in `invoke_before'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:108:in `run_callbacks'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/reloader.rb:96:in `prepare!'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:32:in `instance_exec'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:32:in `run'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
        C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
        C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
        C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
        C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
        C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:350:in `each'
        C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:350:in `call'
        C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
        C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
        C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:60:in `run_initializers'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/application.rb:440:in `initialize!'
        D:/Dev/Test/config/environment.rb:5:in `<main>'
        config.ru:3:in `require_relative'
        config.ru:3:in `block (2 levels) in <main>'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:108:in `eval'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:108:in `new_from_string'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:97:in `load_file'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:67:in `parse_file'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:263:in `app'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:424:in `wrapped_app'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands/server/server_command.rb:36:in `start'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands/server/server_command.rb:145:in `block in perform'
        <internal:kernel>:90:in `tap'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands/server/server_command.rb:136:in `perform'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command/base.rb:178:in `invoke_command'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command/base.rb:73:in `perform'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command.rb:65:in `block in invoke'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command.rb:143:in `with_argv'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command.rb:63:in `invoke'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands.rb:18:in `<main>'
        C:/Ruby33-x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        C:/Ruby33-x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        D:/Dev/Test/bin/rails:4:in `<top (required)>'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/debase-3.0.0.beta.10/lib/debase.rb:224:in `load_protect'
        C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/debase-3.0.0.beta.10/lib/debase.rb:224:in `debug_load'
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:99:in `initialize': no implicit conversion of Pathname into String (TypeError)

        dev = File.new(dev.fileno, mode: MODE, path: filename)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:99:in `new'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:99:in `fixup_mode'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:112:in `open_logfile'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:85:in `set_dev'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:19:in `initialize'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger.rb:593:in `new'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger.rb:593:in `initialize'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/logger.rb:34:in `initialize'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/configuration.rb:237:in `new'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/configuration.rb:237:in `block in default_logger'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/execution_context.rb:41:in `instance_exec'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/execution_context.rb:41:in `handle'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/configuration.rb:232:in `logger'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo.rb:64:in `boot'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/avo-3.14.5/lib/avo/engine.rb:45:in `block in <class:Engine>'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:406:in `instance_exec'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:406:in `block in make_lambda'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:178:in `block in call'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:667:in `block (2 levels) in default_terminator'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:666:in `catch'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:666:in `block in default_terminator'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:179:in `call'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:558:in `block in invoke_before'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:558:in `each'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:558:in `invoke_before'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/callbacks.rb:108:in `run_callbacks'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0/lib/active_support/reloader.rb:96:in `prepare!'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:32:in `instance_exec'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:32:in `run'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
        from C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
        from C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
        from C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
        from C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
        from C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:350:in `each'
        from C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:350:in `call'
        from C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
        from C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
        from C:/Ruby33-x64/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/initializable.rb:60:in `run_initializers'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/application.rb:440:in `initialize!'
        from D:/Dev/Test/config/environment.rb:5:in `<main>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block (2 levels) in <main>'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:108:in `eval'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:108:in `new_from_string'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:97:in `load_file'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:67:in `parse_file'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:263:in `app'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:424:in `wrapped_app'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands/server/server_command.rb:36:in `start'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands/server/server_command.rb:145:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands/server/server_command.rb:136:in `perform'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command/base.rb:178:in `invoke_command'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command/base.rb:73:in `perform'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command.rb:65:in `block in invoke'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command.rb:143:in `with_argv'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/command.rb:63:in `invoke'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/railties-8.0.0/lib/rails/commands.rb:18:in `<main>'
        from C:/Ruby33-x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from C:/Ruby33-x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from D:/Dev/Test/bin/rails:4:in `<top (required)>'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/debase-3.0.0.beta.10/lib/debase.rb:224:in `load_protect'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/debase-3.0.0.beta.10/lib/debase.rb:224:in `debug_load'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/ruby-debug-ide-3.0.0.beta.15/lib/ruby-debug-ide.rb:129:in `debug_program'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/ruby-debug-ide-3.0.0.beta.15/bin/rdebug-ide:202:in `<main>'
```

### System configuration
**Avo version**: 3.14.5^

**Rails version**: 8.0.0^

**Ruby version**: 3.3.1

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
N/A

### Additional context
This may be a problem with logger itself, but I think it's an Avo issue because no other gem I use seems to have the issue

#### Impact
 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by adrianthedev** [comment]
Thanks for reporting this @aldent95. We'll have a look and add a fix.

**Comment by Paul-Bob** [comment]
Hi @aldent95 I wasn't able to reproduce it, it's working as expected on my side.

May be related with this [logger issue](https://github.com/ruby/logger/issues/107).

Could you please open a rails console on that project and try to run `ActiveSupport::Logger.new(Rails.root.join("log", "avo.log"))`?

Let me know the output of it.

Also please include a [reproduction repository](https://docs.avohq.io/3.0/technical-support.html#reproduction-repository) since I wasn't able to reproduce it following the described steps, it doesn't raise that error on my local environment.
