### ISSUE TITLE
Rails API - NoMethodError in Avo::Partners#index

### ISSUE THREAD

**Issue by aaronkelton** [avo-hq/avo#737]
### Context
I'm trying Avo for the first time on a Rails API. I have added `::ActionDispatch::Flash` to the application.rb file. I have installed the basic setup and added a single resource. I am able to access the /avo route and I can see the "Partners" resource in the side menu. However, when I click "Partners", I get the error below. It is correctly hitting the database, but returns a 500 error code. 

Could you suggest something I may be doing wrong or need to change?

```
Started GET "/avo/resources/partners" for 127.0.0.1 at 2022-03-16 11:53:37 -0500
  ActiveRecord::SchemaMigration Pluck (0.9ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Avo::PartnersController#index as HTML
[Avo] Performing request to avohq.io API to check license availability.
  Partner Count (0.7ms)  SELECT COUNT(*) FROM "partners"
  Partner Load (0.9ms)  SELECT "partners".* FROM "partners" ORDER BY partners.created_at desc LIMIT $1 OFFSET $2  [["LIMIT", 24], ["OFFSET", 0]]
  Rendering layout /Users/ak/.rvm/gems/ruby-3.1.1/gems/avo-1.25.0/app/views/layouts/avo/application.html.erb
  Rendering /Users/ak/.rvm/gems/ruby-3.1.1/gems/avo-1.25.0/app/views/avo/base/index.html.erb within layouts/avo/application
  Rendered /Users/ak/.rvm/gems/ruby-3.1.1/gems/avo-1.25.0/app/views/avo/base/index.html.erb within layouts/avo/application (Duration: 30.5ms | Allocations: 7440)
  Rendered layout /Users/ak/.rvm/gems/ruby-3.1.1/gems/avo-1.25.0/app/views/layouts/avo/application.html.erb (Duration: 34.8ms | Allocations: 7543)
Completed 500 Internal Server Error in 293ms (ActiveRecord: 9.2ms | Allocations: 29614)



ActionView::Template::Error (undefined method `new_resources_partner_path' for #<ActionDispatch::Routing::RoutesProxy:0x000000010d4cb478 @scope=#<Avo::PartnersController:0x000000000273a8>, @routes=#<ActionDispatch::Routing::RouteSet:0x000000010b8b7980>, @helpers=#<Module:0x000000010c491eb8>, @script_namer=#<Proc:0x000000010c491fa8 /Users/ak/.rvm/gems/ruby-3.1.1/gems/actionpack-7.0.2.2/lib/action_dispatch/routing/mapper.rb:653 (lambda)>>):
    1: <%= turbo_frame_wrap(params[:turbo_frame]) do %>
    2:   <%= render Avo::Views::ResourceIndexComponent.new(
    3:       resource: @resource,
    4:       resources: @resources,
    5:       models: @models,

actionpack (7.0.2.2) lib/action_dispatch/routing/routes_proxy.rb:50:in `method_missing'
avo (1.25.0) app/helpers/avo/url_helpers.rb:36:in `new_resource_path'
avo (1.25.0) app/controllers/avo/application_controller.rb:28:in `new_resource_path'
avo (1.25.0) app/components/avo/views/resource_index_component.rb:113:in `create_path'
avo (1.25.0) app/components/avo/views/resource_index_component.html.erb:9:in `block (2 levels) in call'
actionview (7.0.2.2) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
```

#### Install and generate resource
```
% rails generate avo:install
       route  mount Avo::Engine, at: Avo.configuration.root_path
      create  config/initializers/avo.rb
      create  config/locales/avo.en.yml

% rails generate avo:resource partner
      create  app/avo/resources/partner_resource.rb
      create  app/controllers/avo/partners_controller.rb
```

#### Flash middleware for API-only app
```ruby
# application.rb
config.middleware.use ::ActionDispatch::Flash
```

### System configuration
**Avo version**: avo (1.25.0)

**Rails version**: Rails 7.0.2.2

**Ruby version**: ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]

### Screenshots

![CleanShot 2022-03-16 at 12 13 38@2x](https://user-images.githubusercontent.com/6170077/158648876-180fe771-f1f3-449d-9baf-c22ac652cf2a.png)

![CleanShot 2022-03-16 at 12 23 12@2x](https://user-images.githubusercontent.com/6170077/158650743-3f24bb38-0369-4d12-933d-68205799c8bf.png)

**Comment by adrianthedev** [comment]
Hey. I reached the same error.
Let me have a look tomorrow to see what can be done. Avo might need a few more things than just the middleware.

Is it possible that you could make that app **not** an api_only app?

**Comment by aaronkelton** [comment]
I will look into what that may require. I never intended for it to have a
web browser interface until recently for admin purposes.

**Comment by adrianthedev** [comment]
I think that if you disable the `api_only` config it should just work.

**Comment by aaronkelton** [comment]
Thank you for your help: changing api_only to false did the trick. I also removed the Flash middleware so it looks like only changing the api_only is required.

I need to dig deeper into any implications or side effects this change may have. But at the moment it seems harmless. 🙌
