### ISSUE TITLE
I got lib/avo/dynamic_router.rb  syntax error when I first try to use.....

### ISSUE THREAD

**Issue by z22919456** [avo-hq/avo#900]
### Describe the bug

```
`require': /Users/arthur/.rvm/gems/ruby-2.6.9/gems/avo-2.5.1/lib/avo/dynamic_router.rb:16: syntax error, unexpected '.', expecting end (SyntaxError)
        .map do |resource|
        ^
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/activesupport-6.0.5/lib/active_support/dependencies.rb:324:in `block in require'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/activesupport-6.0.5/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/activesupport-6.0.5/lib/active_support/dependencies.rb:324:in `require'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/avo-2.5.1/lib/avo.rb:42:in `<top (required)>'
        from /Users/arthur/.rvm/rubies/ruby-2.6.9/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `require'
        from /Users/arthur/.rvm/rubies/ruby-2.6.9/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
        from /Users/arthur/.rvm/rubies/ruby-2.6.9/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `each'
        from /Users/arthur/.rvm/rubies/ruby-2.6.9/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
        from /Users/arthur/.rvm/rubies/ruby-2.6.9/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `each'
        from /Users/arthur/.rvm/rubies/ruby-2.6.9/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `require'
        from /Users/arthur/.rvm/rubies/ruby-2.6.9/lib/ruby/site_ruby/2.6.0/bundler.rb:114:in `require'
        from /Users/arthur/Documents/saracares/config/application.rb:9:in `<top (required)>'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/railties-6.0.5/lib/rails/command/actions.rb:22:in `require'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/railties-6.0.5/lib/rails/command/actions.rb:22:in `require_application!'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/railties-6.0.5/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/railties-6.0.5/lib/rails/commands/generate/generate_command.rb:10:in `help'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/railties-6.0.5/lib/rails/command/base.rb:69:in `perform'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/railties-6.0.5/lib/rails/command.rb:46:in `invoke'
        from /Users/arthur/.rvm/gems/ruby-2.6.9/gems/railties-6.0.5/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

### Steps to Reproduce
1. add gem file
2. bundle 
3. run `rails g --help` , start server  or start console

Just that, nothing spacial

### Expected behavior

It should start server normally

### System configuration
**Avo version**:
v2.6.0 and v2.5.1

**Rails version**:
6.0.5

**Ruby version**:
ruby-2.6.9 [ arm64 ]

**License type** (Community or Pro):
Community

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [ ] low urgency

**Comment by z22919456** [comment]
I fixed it, when I upgrade my ruby to ruby-2.7.5
