### ISSUE TITLE
Undefined method in Rails Intialization process after installing Avo

### ISSUE THREAD

**Issue by paul-oms** [avo-hq/avo#987]
### Describe the bug

After adding Avo to the Gemfile of an existing rails app and running bundle install, every rails command (e.g `bin/rails s`) gives the following error.

```
.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/app/components/avo/panel_component.rb:6:in `<class:PanelComponent>': undefined method `renders_one' for Avo::PanelComponent:Class (NoMethodError)
```

This is traced back to `Rails.application.initialize!` My guess is that this is something app/environment specific so won't be reproducible? But would appreciate any pointers to help track this down as we don't have this issue with any other dependencies.

### Steps to Reproduce
From existing Rails 7.0.0 app on Ruby 3.1.0
1. Add gem 'avo' to your Gemfile
2. Run bundle install.
3. Use any bin/rails command (e.g. `bin/rails start`, `bin/rails generate avo:install`)

### Expected behavior
Rails should initialize

### Actual behavior
```
$ bin/rails g

/Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/app/components/avo/panel_component.rb:6:in `<class:PanelComponent>': undefined method `renders_one' for Avo::PanelComponent:Class (NoMethodError)

  renders_one :tools
  ^^^^^^^^^^^
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/app/components/avo/panel_component.rb:3:in `<main>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:88:in `register'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:27:in `require'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:95:in `cget'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:231:in `block (2 levels) in eager_load'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:18:in `ls'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:226:in `block in eager_load'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:211:in `synchronize'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:211:in `eager_load'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/autoloaders.rb:32:in `each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application.rb:497:in `eager_load!'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/lib/avo/dynamic_router.rb:4:in `routes'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/config/routes.rb:35:in `block (2 levels) in <main>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/mapper.rb:871:in `scope'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/config/routes.rb:21:in `block in <main>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/mapper.rb:625:in `instance_exec'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/mapper.rb:625:in `block in with_default_scope'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/mapper.rb:871:in `scope'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/mapper.rb:624:in `with_default_scope'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/route_set.rb:424:in `eval_block'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/route_set.rb:408:in `draw'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/config/routes.rb:1:in `<main>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:50:in `block in load_paths'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:50:in `each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:50:in `load_paths'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:24:in `reload!'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:38:in `block in updater'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/file_update_checker.rb:83:in `execute'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:13:in `execute'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/finisher.rb:156:in `block in <module:Finisher>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/initializable.rb:32:in `run'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application.rb:372:in `initialize!'
	from /Users/user_name/Side/oms/app/config/environment.rb:5:in `<main>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:88:in `register'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application.rb:348:in `require_environment!'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/command/actions.rb:28:in `require_environment!'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/commands/generate/generate_command.rb:10:in `help'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/commands/generate/generate_command.rb:19:in `perform'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/command/base.rb:87:in `perform'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/command.rb:48:in `invoke'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/commands.rb:18:in `<main>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:105:in `register'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bootsnap-1.9.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from bin/rails:4:in `<main>'
```

### System configuration
**Avo version**: 2.4.0, 2.5.0, 2.9.0

**Rails version**: 7.0.0

**Ruby version**: 3.1.0

**License type** (Community or Pro): Community

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment]
Hey @paul-oms, are you using `view_component` in your app? do you have it present in your `Gemfile`? I think the `renders_one` method has been added at some point. Maybe update `view_component` in your app.

I launched Avo on [Product Hunt](https://www.producthunt.com/posts/avo-for-rails) (any feedback and comments help a lot BTW) and my efforts go there today. But I'm happy to help more hands-on from tomorrow 💪

**Comment by paul-oms** [comment]
Thanks @adrianthedev, just gave Avo an upvote on PH :) 

`view_component` is in gemfile.lock (as an avo dependency). I've tried adding it as it's own dependency alongside avo, and I get the same error. Adding `view_component` to the gemfile without avo works fine, I can generate view_components no problem. 

I thought it might be to do with bootsnap, but disabling that still leads to the same error, but the stack trace is a little different:

```
$ rails s

=> Booting Puma
=> Rails 7.0.1 application starting in development
=> Run `bin/rails server --help` for more startup options
Exiting
/Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/app/components/avo/panel_component.rb:6:in `<class:PanelComponent>': undefined method `renders_one' for Avo::PanelComponent:Class (NoMethodError)

  renders_one :tools
  ^^^^^^^^^^^
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/app/components/avo/panel_component.rb:3:in `<top (required)>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:27:in `require'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:27:in `require'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:95:in `cget'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:231:in `block (2 levels) in eager_load'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader/helpers.rb:18:in `ls'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:226:in `block in eager_load'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:211:in `synchronize'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.3/lib/zeitwerk/loader.rb:211:in `eager_load'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/autoloaders.rb:32:in `each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application.rb:497:in `eager_load!'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/lib/avo/dynamic_router.rb:4:in `routes'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/config/routes.rb:35:in `block (2 levels) in <top (required)>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/mapper.rb:871:in `scope'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/config/routes.rb:21:in `block in <top (required)>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/mapper.rb:625:in `instance_exec'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/mapper.rb:625:in `block in with_default_scope'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/mapper.rb:871:in `scope'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/mapper.rb:624:in `with_default_scope'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/route_set.rb:424:in `eval_block'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.1/lib/action_dispatch/routing/route_set.rb:408:in `draw'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/avo-2.9.0/config/routes.rb:1:in `<top (required)>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:50:in `load'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:50:in `block in load_paths'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:50:in `each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:50:in `load_paths'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:24:in `reload!'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:38:in `block in updater'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.1/lib/active_support/file_update_checker.rb:83:in `execute'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/routes_reloader.rb:13:in `execute'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application/finisher.rb:156:in `block in <module:Finisher>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/initializable.rb:32:in `run'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/application.rb:372:in `initialize!'
	from /Users/user_name/Side/oms/app/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/commands/server/server_command.rb:36:in `start'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/command/base.rb:87:in `perform'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/command.rb:48:in `invoke'
	from /Users/user_name/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by paul-oms** [comment]
Managed to track it to this line: https://github.com/avo-hq/avo/blob/fd6189fc63a970a0224f0dbcbe7e96e521d22a19/lib/avo/dynamic_router.rb#L4

If I remove that from my locally installed gem everything runs fine. 

It comes from this PR: https://github.com/avo-hq/avo/pull/800

We are disabling eager loading in our dev environment, but testing it with `eager_load = true`, with Avo, it runs fine. So not sure why Avo calling `Rails.application.eager_load!` is causing a problem.

**Comment by adrianthedev** [comment]
It eager loads the files so it can find the descendants of `BaseResource` (and others). IMHO, it doesn't (shouldn't) work without eager loading.

```ruby
class UserResource < Avo::BaseResource
end
```

**Comment by adrianthedev** [comment]
I'm going to close this for now. Feel free to reopen it.
